### ISSUE TITLE
109 upgrade blue body

### ISSUE THREAD

**Issue by numxxviii** [LegionDark/Issues#1043]
Date & Time: 8/3/2016 10:37

FFXI Client Version (use /ver): 30160602_0

Server's Expected Client Version matches, yes/no? (use @ecv): no

Character Name: Numxxviii

Nation: Bastok

Job(level)/Sub Job(level): blu/rdm

NPC or Monster or item Name: Prishe

Zone name & Coordinates (use @where): x537 y500 z591 (123)

ffxiah.com link (for items issues only): n/a

Multi-boxing? (multiple clients on same connection): same

Steps To Reproduce / any other info: trade prishe the +2 body and the 30 items and -0-
+working i have all 10 titles and 3 lunars i upgraded feet legs head to 109
+in the last week or so but not working on the body

**Comment by ecv** [comment]
Feel shame, @numxxviii !

**Comment by ecv** [comment]
Experience the derision of your peers!

**Comment by R3P0FFXI** [comment]
closed because user cannot grasp the simple concept of dont modify the fucking template @ecv my apologies for the level of stupid you are getting here

**Comment by ecv** [comment]
lol np brah i am amused

**Comment by R3P0FFXI** [comment]
@ecv you ant to be even more amused click new issues and look at the template @TeoTwawki created for them thats what makes this even more amazing. They do more work deleting things from the template instead of just filling shit out.

**Comment by numxxviii** [comment]
So you know I was only doing what someone was trying to help me as I had
not done it be for but I'm good it is a waste of time playing a GAME with
ppl like this . Have a good day

**Comment by ecv** [comment]
Honestly I can sorta see how the backticks around the at-signed in-game commands can confuse folks here. I'm surprised that your game uses at-signs for commands instead of !bangs or /slashes, like I'm used to. 

All good here, tho.

**Comment by TeoTwawki** [comment]
@ecv I tried to get the parent project to stop using `@` and was basically met with "we don't need this change because it would inconvenience me to get used to a different key" so they reverted the merge..

Bunch of homebrew game servers running off the same base code, and the more customization we jam in the more extra work there is to deal with to re-sync up the core when we pull down changes.

**Comment by ecv** [comment]
Word. Changing behaviors is hard, I dig it. 

Maybe don't force it for existing users, but let / be the default for new users? Like, it becomes a prefs option, defaults to '/' and users change it back; or maybe defaults to '@' for the first release and changes to '/' next', so they don't have to do anything.

Either way, I'm resigned to receiving the spam occasionally, it's amusing.

**Comment by TeoTwawki** [comment]
I can't use a slash for server side commands sent from client, the client is coded not to send it because those are in client commands (and client end is close-sourced\*). I did temporarily leave the `@` working while adding the alternative key with some commenting to indicate its use was being deprecated and that got merged, but a different project member immediately reverted that change.

##### \*I really hate the client, but creating a foss alternative isn't in the cards for the foreseeable future.
