### ISSUE TITLE
Telepath's crafting imports

### ISSUE THREAD

**Issue by antabusdark** [LegionDark/Issues#1050]
Date & Time: 08/08/2016 - 1:46PM EST

FFXI Client Version (use /ver): 30160329_0

Server's Expected Client Version matches, yes/no? (use @ecv): yes

Character Name: Telepath

Nation: San d'Oria

Job(level)/Sub Job(level): BRD84/(sub locked)

NPC or Monster or item Name: N/A

Zone name & Coordinates (use @where): North San d'Oria - MH - X:0 Y:0 Z:0

ffxiah.com link (for items issues only): N/A

Multi-boxing? (multiple clients on same connection): no

Steps To Reproduce / any other info:

Hello,

This ticket is for crafting imports purpose.

Here, you will find the link to my application including the picture of my previous crafts:

http://legiondark.com/forums/viewtopic.php?f=37&t=1665

Is it possible to keep sub crafts? (i only have gsmith 100 btw)

Thank you for you help and have a good day.

**Comment by Genesis-Legion** [comment]
Since you're coming from a private server you'll have to pick one as outlined here http://legiondark.com/forums/viewtopic.php?f=37&t=398
"Craft skills WILL NOT be imported. Instead, after your character is imported, contact a GM to have one of the craft levels from your exported profile restored."
And in the future if you need to fill out bug reports, please don't mess with the formatting of the template (where it says `@ecv` and `@where` as using @ alerts people that they've been mentioned and those people have no relation to this project, Thanks.

**Comment by antabusdark** [comment]
Ok np, then i'll keep goldsmithing.
Thank you.

**Comment by PikaFox** [comment]
Set player's Goldsmithing.
