### ISSUE TITLE
Possible TP hacker to claim mobs 

### ISSUE THREAD

**Issue by Hazed69** [LegionDark/Issues#1052]
**Date & Time**: 8/9/16 20:36

**FFXI Client Version (use `/ver`)**: 30160629_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: no

**Character Name**: Hazed

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99thf/dnc49

**NPC or Monster or item Name**: NPC(tanzanite mobs)

**Zone name & Coordinates (use `@where`)**: x-136 y 0 z-56 (60)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Had player come in and start camping over me fine shit happens but had her upstairs at tanzanite mob closest to la theine exit for Zilart Headstone. Fleed downstairs to find her on that one at 2% She claims she fleed over a 2 min run on flee speed (impossible) I am sure this person is lying and would like a GM to investigate please. Thanks. Left players name out but did screenshot her downstairs on 2nd npc at low health doing 6-9 damage a swing.

**Comment by R3P0FFXI** [comment]
@Hazed69 Kinda missing the key point here of a ticket we can do no investigations without a players name.

**Comment by Hazed69** [comment]
players name was steliokontos

**Comment by Samikana** [comment]
Player was investigated, no evidence of TP hacking.  Please submit another report if you find any more evidence of this happening (and possibly also record it.)

**Comment by TeoTwawki** [comment]
@Samikana we shouldn't tell people what we do/don't find, lets people try to infer what we can/can't see (same reason retail doesn't inform people) and we KNOW this player base already expends a lot of effort actively looking for ways to slip shit past the radar.

**Comment by Nightrideroverwatch** [comment]
I disagree because Hazed falsely accused this poor player and we ended up dropping her from link shell cause her name was here for everyone to see , and from what I here nobody would do anything with this player cause she was  accused of cheating cause someone got mad at some competition at least in this case it needed to be shown that she was innocent and what of the damage to the player's reputation in game ?

**Comment by TeoTwawki** [comment]
And I disagree because the player should not have even known anything was being investigated, let alone **their entire linkshell**. :angry: :anger:

**Comment by Nightrideroverwatch** [comment]
You should have disagreed 22 days ago , but I understand you were just being a good lap dog and didn't want to bite your Master. Good thing there is at least one reasonable GM still around with common sense.

**Comment by TeoTwawki** [comment]
> I understand you were just being a good lap dog and didn't want to bite your Master
That's extremely disrespectful, at this was the first I've heard of any in game accusing going on by staff.

**Comment by TeoTwawki** [comment]
> I understand you were just being a good lap dog and didn't want to bite your Master

That's extremely disrespectful, ~~and this was the first I've heard of any accusing going on by staff.~~

Edit, re-edited because you appear to have editted: you know what would be nice? If *players* had some GD common sense. First we're supposed to investigate without knowing being told who the hell is allegedly cheating. Then we have to explain wtf PMs mean. Then we get accused of causing untold suffering and damage to reputations. If your LS really booted someone just because of Haze, they are morons. I could swear you wrote "Halsey" before that edit but github doesn't keep a record. You can still F right off for talking to me like that.

**Comment by R3P0FFXI** [comment]
@Nightrideroverwatch Hiding behind anonymity of github and creating an account just to respond to this is classless and low. We are not a professional staff, all of us have jobs and do this for what is supposed to be fun.  I really dont care if you decide to stay or leave this server with the way you are addressing people here. If you want to be constructive and add to things much less find a better way to investigate that does not cost me more money, or the staff more time I am open for it. We will investigate every claim of cheating using the guidelines we have set in place.

Nightrideroverwatch
Joined on Aug 31, 2016
