### ISSUE TITLE
AF claim slip duplicate (?)

### ISSUE THREAD

**Issue by Mizuharu** [LegionDark/Issues#1077]
**Date & Time**: 
9/5/2016; September 5th 2016 (occur'd last night. Submitting report on 9/6/2016)

**FFXI Client Version (use `/ver`)**: 
30160728_0
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160728_0

**Character Name**: 
Zixum

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
SCH60/RDM30

**NPC or Monster or item Name**: 
Caruvinda (Armor Storage NPC)
Scholar's Bracers
Scholar's Loafers
Scholar's Gown
Scholar's M.board
Scholar's pants
Scholar's armor claim slip

**Zone name & Coordinates (use `@where`)**: 
Lower Jeuno; X:21 Y:-1 Z:40

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/15004/scholars-bracers
http://www.ffxiah.com/item/15748/scholars-loafers
http://www.ffxiah.com/item/16140/scholars-mboard
http://www.ffxiah.com/item/16311/scholars-pants
http://www.ffxiah.com/item/14580/scholars-gown

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
1) Retrieve AF gear from the storage NPC.
2) Attempt to store the gear
3) NPC says you already hold a claim slip for that armor

I was playing with Scholar last night and, when I went to return the AF gear to the NPC, he claimed I already had a claim slip. I checked and, I indeed had a claim slip. Thinking that maybe the slips auto-replace on logout/login (since I had d/ced an hour before this), I floored the AF gear for inventory space. Fast forward to today, and the claim slip is no longer in my key items. Wish I had taken a screen shot :< Sorry.

**Comment by Genesis-Legion** [comment]
Claim slips are permanent here afaik, can just toss your set and get the AF again if you ever need to

**Comment by Mizuharu** [comment]
Ah, then I should edit this report since I no longer have a claim slip? I have a screenshot for that...
![zixum_2016 09 06_144121](https://cloud.githubusercontent.com/assets/21317503/18288236/2df02b9c-7440-11e6-818b-371bec069923.png)

**Comment by Samikana** [comment]
I'm going to go ahead and give @Mizuharu his claim slip back, @TeoTwawki is either going to have to offer and explanation or look into it.

**Comment by Samikana** [comment]
I'm going to go ahead and give @Mizuharu his claim slip back, @TeoTwawki is either going to have to offer and explanation or look into it.

**Comment by TeoTwawki** [comment]
The KI's are given just by clicking the NPC that stores the items. All of them. Its literally impossible to not have them all at once.

**Comment by TeoTwawki** [comment]
This basically means your armor is already stored at all times even after you retrieved it. Its not a bug. Its me giving everyone free AF because I no way am I fixing all the AF quests for Darkstar.

**Comment by Mizuharu** [comment]
@TeoTwawki I talked to the NPC before submitting this report, and did not receive a new claim slip. Every other claim slip was available; only SCH was missing.

**Comment by TeoTwawki** [comment]
`player:addKeyItem(1969);` Is right there in its script. That adds the KI for SCH everytime you speak to him.
`SCHOLARS_ATTIRE_CLAIM_SLIP               = 1969;`
Per your own issue report:
> I was playing with Scholar last night and, when I went to return the AF gear to the NPC, he claimed I already had a claim slip. I checked and, I indeed had a claim slip.
You were trying to return gear while the NPC thinks its already stored *because you had the claim slip already*.

Later you've dropped your armor and no longer have the slip somehow: re-talking to him will recreate the slip. The only thing a GM would do is *run this exact same command that the NPC does.*

**Comment by TeoTwawki** [comment]
`player:addKeyItem(1969);` Is right there in its script. That adds the KI for SCH everytime you speak to him.
`SCHOLARS_ATTIRE_CLAIM_SLIP               = 1969;`
Per your own issue report:
> I was playing with Scholar last night and, when I went to return the AF gear to the NPC, he claimed I already had a claim slip. I checked and, I indeed had a claim slip.

You were trying to return gear while the NPC thinks its already stored *because you had the claim slip already*.

Later you've dropped your armor and no longer have the slip somehow: re-talking to him will recreate the slip. The only thing a GM would do is *run this exact same command that the NPC does.*

**Comment by Mizuharu** [comment]
Halsey gave me the claim slip a while ago, and I just went to the storage NPC in Lower Jeuno. I got my SCH gear back and talked to him; this time the slip showed back up. Idk why it didn't before. Sorry for the touble. :/
