### ISSUE TITLE
Bastok 3-1 Four Musketeers

### ISSUE THREAD

**Issue by Tanild** [LegionDark/Issues#115]
**Date & Time**: 6/23/2015
**Frequency**: Twice
**FFXI Client Version**: 30150508_8
**Character Name**: Splinter & Elm
**Race**: Galka and Hume
**Main Job**: NIN and BRD
**Sub Job**: DNC and WHM
**Area & Coordinates**: Beaudeux (E-7)
**Party or Solo**: Party
**NPC Name**: Naji (spawns when zoning to Pashow
**Monster Name**: Copper Quadav
**Steps To Reproduce The Issue**: Trying to do Bastok Mission 3-1 The Four Musketeers. Have gotten the proper cutscenes and am have killed 20 Copper quadavs but when I zone to finish the mission the custscene says that I haven't killed enough. Sami said to relog and do it again which didn't fix the issue.

**Comment by R3P0FFXI** [comment]
See a Gm when you are on so we can look at your mission to make sure everything completed as required.

**Comment by TeoTwawki** [comment]
If you are getting the cs that says you didn't kill enough, then its hasn't counted off 20 coppers. If you aoe 1 shot kill unclaimed mobs they won't count, due to quirks in dsp's mob death handling. If you are multi boxing, that can also cause the variable to not set properly. To ensure your kills count, make sure the mobs name goes red before killing it, and make sure all characters from your ip address (my nephew plays on same connection I do, and we run into same issues as I would dual boxing an alt) have fully closed out the client out (use `/shutdown` ) and only your current character has logged back in.

**Comment by TeoTwawki** [comment]
@R3P0FFXI we really, *really* need a known issues sticky for people to start collecting these things into.

**Comment by R3P0FFXI** [comment]
Please advise if still an issue after todays update

**Comment by Tanild** [comment]
It still didn't work and I did it solo by myself, no alt. It was a fresh restart and only logged onto my main.

**Comment by Loki79** [comment]
@R3P0FFXI  whats up with this?
