### ISSUE TITLE
White Stratum Abyssite III cant UP White Stratum Abyssite IV

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#1160]
**Date & Time**: 10/13/2016

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
![qq 20161013123149](https://cloud.githubusercontent.com/assets/13742980/19336918/0751913c-9142-11e6-8f3b-ba52323ebd6a.png)

**Character Name**: onlyyou/ayun

**Nation**: sandy

**Job(level)/Sub Job(level)**: WHM/RdM

**NPC or Monster or item Name**: white Stratum Abyssite III

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
![qq 20161013123149](https://cloud.githubusercontent.com/assets/13742980/19336938/5349b5ec-9142-11e6-8971-8357057f9644.png)

kill  white III 3nms  cant up to white IV

**Comment by TeoTwawki** [comment]
Go back to the voidwatch officer, you skipped steps.

**Comment by qiganggang** [comment]
![qq 20161013174904](https://cloud.githubusercontent.com/assets/13742980/19344589/5d7fe146-916d-11e6-9194-26756995cbe4.png)
No cs No UP

**Comment by TeoTwawki** [comment]
You don't even have the quest flagged at all.

**Comment by TeoTwawki** [comment]
Its not broken - you aren't ON it to finish it

**Comment by TeoTwawki** [comment]
O;ll walk you through later. I need sleep.

**Comment by qiganggang** [comment]
OK i wait you

**Comment by TeoTwawki** [comment]
@LegionDark/gm player not only didn't have quest flagged, but the preceding quest never finished because of the multiboxing bug. I forced their variable for the preceding quest since their current variables would be impossible to attain if they hadn't done it, but this can recur at any time without warning to anyone who runs multiple characters at once on the same socket and cannot be fixed. The best we can ever do for multibox related glitches is reset the quest so they can repeat it.

As Onlyyou and Ayun have now been able to get the next CS event, I am closing this issue.
