### ISSUE TITLE
Adamanturd no has Sipar :(

### ISSUE THREAD

**Issue by TwIzTiD2469** [LegionDark/Issues#1192]
**Date & Time**: 10/20/16

**FFXI Client Version (use `/ver`)**: retail

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Boombastic

**Nation**: Sandy

**Job(level)/Sub Job(level)**:99THF/NIN 

**NPC or Monster or item Name**: Adamantoise

**Zone name**: Valley of Sorrows

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/12361/sipar

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Killed it a few times trying to get shield for my galka mule just because. Was curious as to why it wouldn't drop so went and checked our item db and he just don't drop it anymore :( also unsure of the item mods too, but it's suppose to block like 98% but for 1-5% dt. mostly for skillup purposes.

**Comment by TeoTwawki** [comment]
@R3P0FFXI "There is no AH history to display!" according to the AH tool on the website. So not a drop currently and not sold by bot. Rather than just making it a drop or adding to the bot though, I'd like to do something special but also quick easy and scripted, with this. will talk to you about it on IRC later.
