### ISSUE TITLE
Ru'aern Seems to Have Permanent Hundred Fists Effect

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1204]
**Date & Time**: 10/25/16

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: 99 Rdm/ 49 Whm

**NPC or Monster or item Name**: Ru'aern

**Zone name**: Al'Taieu

**Coordinates (use `$where`)**: 0, -3, -734

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

Spawn mobs for CoP 8-1.

Mobs seem to never stop attacking, or have minimal delay.

Wiki doesnt list them having obscene attack rate.

**Comment by PikaFox** [comment]
Spawned them a 2nd time, they dont seem to have it this time. I am not sure what changed, so ill leave this still up as the issue did exist once.

**Comment by TeoTwawki** [comment]
This probably has to do with the only one in mob_pools being designated a monk.

**Comment by PikaFox** [comment]
Quite possibly, but it will be all 3 of them, and all 3 shouldnt be mnk. Spawned the 2nd set, and they again had near 0 attack delay.

**Comment by TeoTwawki** [comment]
Yeah thats kinda my point. recall what happened with paladin Maat, frenzy punching because his Ai thinks he should be a monk with invalid delay.

**Comment by PikaFox** [comment]
The issue might be more widespread... a Woodtroll Monk in Wajaom Woodlands had near 0 attack delay as well. It might be quite a lot of mobs that use h2h recently.

**Comment by TeoTwawki** [comment]
There's a delay bug with anything that has its cmbSkill column in the database set above zero (so every monk, and a handful of non monks with special damage types) can hit this problem. And many have a wrong base delay as well so if martial arts trait is applied they then have effectively zero delay, even without any other bug. Theres an open dsp issue for the cmbSkill problem. The issue was originally opened for a dragoon mob someone tried to set to use piercing dmg. On retail mobs don't differentiate types like that - they all count as the same no matter what the mobs graphic is, lol.

**Comment by R3P0FFXI** [comment]
@PikaFox I believe @TeoTwawki has resolved this for the next update
