### ISSUE TITLE
Blurred Weapons Missing All Modifications

### ISSUE THREAD

**Issue by atom0s** [LegionDark/Issues#1206]
**Date & Time**: 10/27/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes.

**Character Name**: Atomos

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: Not needed.

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: 

None of the craftable blurred weapons have any modifications implemented on them, making them utterly useless.

**Comment by TeoTwawki** [comment]
Notes:
- Do **not** try to code any of teh additional effects. I'm 90% done witha  related change and will have them handled when I finish.
- I'd rather we didn't try to put the stats into DSP immedatly, because some moron will see ti immediately decide to code the additional effects in darkstar while I'm trying to finish up a refactor that requires undoing that garbage.

**Comment by R3P0FFXI** [comment]
Leaving open until @TeoTwawki is able to finish the effects all current existing mods in DSP are on the weapons
