### ISSUE TITLE
Oak Pole Woodworking Guild Points

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1236]
**Date & Time**: 
11/16/2016 15:55

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99Thf/49Dnc

**NPC or Monster or item Name**: 
Oak Pole

**Zone name**: 
North Sandy

**Coordinates (use `$where`)**: 
-188 11 263 (90)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/17098/oak-pole

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Woodworkers guild only awards 240 total guild points for oak poles. The guild points value is supposed to be 1,560 each, or 5,360 total. The following was taken before I even attempted to trade in items for today.
![immortality_2016 11 16_155322](https://cloud.githubusercontent.com/assets/22607214/20367440/76debfd4-ac1d-11e6-88b2-be20a807ec01.png)

**Comment by R3P0FFXI** [comment]
@JessLand86 please report this issue to Darkstar this is something which would need to be fixed in DSP

**Comment by JessLand86** [comment]
I'll just close the ticket then, since DSP isn't gonna be pulled anytime in the foreseeable future.

**Comment by TeoTwawki** [comment]
At both of you:

If nobody reports stuff to dsp nothing gets fixed over there, so then its not there for us to pull updates in. To be fair, players generally can't be expected to know whats a dsp bug and whats a legion bug with the level of custom thats in legion, and the only reason I have asked some ppl to report a few things is because nobody in legion has been reporting those bugs that get tagged as dsp bugs. Same thing happens at nearly all the other private servers: nobody is reporting it **to dsp** so its not getting fixed.

But just closing doesn't help anybody, and sometimes leads to duplicate reports form people who didn't see it was already reported.
