### ISSUE TITLE
CoP 2-3 Distant Beliefs (Frozen in ending cs)

### ISSUE THREAD

**Issue by Azurewrathx** [LegionDark/Issues#1253]
**Date & Time**: Thursday Nov 24, 2016    2:32am  CST

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Azurewrath

**Nation**: bastok

**Job(level)/Sub Job(level)**: MNK77/DNC38

**NPC or Monster or item Name**: Justinius

**Zone name**: Tavnazian Safehold

**Coordinates (use `$where`)**: X:78  Y:-34  Z:67    (166)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: CoP 2-3 Distant Beliefs ending cs with Justinius to move onto CoP 2-4.  I'm frozen in the cs staring at the taru with green hair.  I've tried force dc, i've tried *tele dem and re-entering zone and i still get frozen in the same spot.

**Comment by TeoTwawki** [comment]
9 out of 10 times this is a an addon or plugin, in rarer cases file corruption.

Try loading up the game from xiloader on the commandline, without either of ashita or windower, and see if the cs event is able to finish then. [Be sure to run the command prompt as admin.](https://techjourney.net/how-to-open-elevated-command-prompt-as-administrator-with-admin-privileges-in-windows/)
In my own case my command would look like this:
`D:\ashita\ffxi-bootmod\pol.exe --server legiondark.com`
Because I'm an ashita user and I tossed it on drive D, and it comes with the loader renamed to pol.exe

**Comment by Azurewrathx** [comment]
Tyvm, that did the trick.  When i got past the spot on the cs using your method i intentionally crashed the game and tried turning off all my addons and plugins on the windower.  I was able to get through the cs this way also.  Ty TeoTwawki!!!

**Comment by TeoTwawki** [comment]
Glad your past the stuck spot :)

I don't know exactly which plugin/addon causes it, but it seems to happen on cs's that include the 3 taru kids from CoP more than any other. I rarely get reports of this issue that aren't that one you were just one, in fact.
