### ISSUE TITLE
Grotto Pugil - Incorrect Detect

### ISSUE THREAD

**Issue by Devrin9** [LegionDark/Issues#1259]
**Date & Time**: 
12/2/2016

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Devrin

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
WAR31/MNK15

**NPC or Monster or item Name**: 
Grotto Pugil

**Zone name**: 
Sea Serpent Grotto

**Coordinates (use `$where`)**: 
H11-I11

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Simply use character similar to my level and enter while sneaked. There is a single Pugil that will always aggro even when Sneak is applied. Once you apply invisible, he does not aggro. Killed me twice... so much fun.

**Comment by TeoTwawki** [comment]
Can you recheck this pugil today now that maintenance is done? Also you didn't specify your `/ver` output in the template. This is relevant because the server can theoretically think its something other than a pugil, but on the client says mob with that ID should be a pugil. Darkstar itself (the software the server runs) may have an old/outdated entry there even if your version matches the server so it helps me narrow down which bug we have if I know what version it was at a glance without having to dig.

**Comment by TeoTwawki** [comment]
A bunch of mobs got detection corrections today, so I am hoping this is already resolved.

**Comment by Devrin9** [comment]
I just confirmed that this was fixed! Much obliged. This should make the Ninja quests easier for many.

by the way, my version is 30161004_1
