### ISSUE TITLE
Maze of Shakhrami excavation points are not appearing in game or on wide scan - this breaks the DRG job quest

### ISSUE THREAD

**Issue by Saelys** [LegionDark/Issues#128]
**Date & Time**: Monday June 29th, 4:10am
**Frequency**: Ongoing
**FFXI Client Version**: 30150508_8
**Character Name**: Saelys
**Race**: Mithra
**Main Job**: Paladin - PLD
**Sub Job**: Monk - MNK
**Area & Coordinates**: Maze of Shakhrami
**Party or Solo**: Solo
**NPC Name**: N/A
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Enter Maze of Shakhrami area, no points present/points never spawn

**Comment by R3P0FFXI** [comment]
Check with users who have completed and opened DRG and see what they have done for this issue. There are many who play DRG on server

**Comment by Saelys** [comment]
If I ever get the chance to see one who didn't get DRG from a server transfer, I guess I will try to ask and hopefully they will tell me.

**Comment by R3P0FFXI** [comment]
Caliburn got it on this server, please try again now as we just updated

**Comment by TeoTwawki** [comment]
I unlocked drg the old fashioned way too..Took me awhile to find the point because DarkStar only has 1 spawn at a time and its randomly selected pos was off in middle of nowhere among the high lv mobs. Had to wander around a lot before I could see it on widescan. Its possible that these no longer show up on widescan as well - I remember seeing changes to that awhile back, I'll have to read the commit log later to see if that is what was done. If that turns out the case I'll see if I can undo that, at least until there are multiple points up all over like retail...Its just too much to expect people to blindly hunt for a single point. I might also force the one in maze of Shakrami to always be near the entrance because of the number of people having difficulty finding it. Self assigning this issue and will keep an eye on it.

**Comment by Saelys** [comment]
I was assisted by a GM, Caliburn today in finding the point.  There was indeed only one.  Either I missed it the first time around which seems possible or it reset with the update. Either way, the item dropped, allowing me to continue.
