### ISSUE TITLE
Sirrush Abyssea Misareaux

### ISSUE THREAD

**Issue by Devilotte** [LegionDark/Issues#1288]
**Date & Time**: 
12/28/2016 4:20PM PST

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Detienne

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
99COR/49DNC

**NPC or Monster or item Name**: 
Sirrush

**Zone name**: 
Abyssea - Misareaux

**Coordinates (use `$where`)**: 
X:349 Y:16 Z:-421 (60)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
??? used to pop Sirrush is missing

**Comment by Heepster03** [comment]
Okay, I found the ???. They are located at (J-11) right next to the Peistes.

**Comment by TeoTwawki** [comment]
@R3P0FFXI positions have been messed up ever since SE decided to add multiple pop points all over abyssea. What needs to happen is someone verify that all the positions are in on DSP and then number them in order in the sql, followed by renaming the scripts to match the new numbering (most of the ones in DSP do not have a number *at all* but the newer ones were added in between the ones we already had).
