### ISSUE TITLE
Unable to sign onto smithing guild

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1307]
**Date & Time**: 1/12/2017 7:12am

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Ghemp

**Zone name**: Metalworks bastok

**Coordinates (use `$where`)**: x:-110 y:2 Z:27 (129)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Trying to sign onto the smithing guild.  Both the one in bastok and sandy keep repeating the first dialogue, signing me on and giving me fire crystal over and over again.

**Comment by spectre99** [comment]
Just an update, I decided to trade the test item anyway, and it gave me the rank of recruit, but when I click the npc again it gives me the same 'sign up' dialogue again.

**Comment by spectre99** [comment]
One more update, it seems that despite the sign up dialogue I can still turn in items to climb rank, but the other npcs who give synth support won't talk to me and don't recognize me as a member.

**Comment by TeoTwawki** [comment]
For awhile the variable the "joined" guilds were stored in had been broken, and now I expect a lot of people to have this now that its been corrected since their var will have been set to the wrong value. The easiest solution makes you need to re-join any and all guilds.

@LegionDark/gm the varname is `Guild_Member` at zero player is a member of no guilds at all. Every time a guild is joined and the crystal given, 1 single bit of its mask will flip. I think smithing is the 9th bit.

**Comment by TeoTwawki** [comment]
was hot fixed and player fix, but others may have corrupt var - have to handle on a case by case basis if anyone reports loss of guild features or having had to re-signup
