### ISSUE TITLE
-179 AGI after Kaggen debuff

### ISSUE THREAD

**Issue by Walkersauce** [LegionDark/Issues#1339]
**Date & Time**:  01/28/2016.1300

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: YES

**Character Name**: Jaundice

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99BLU/49RDM

**NPC or Monster or item Name**: Kaggen

**Zone name**: Qufim Island

**Coordinates (use `$where`)**: X:162 Y:-20 Z:166 (128)

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: YES

**Steps To Reproduce / any other info**: Macerating Bile - The AGI debuff never wears off over time. Relogging is the only way to fix. Ashen and Kiari received the same issue.

**Comment by TeoTwawki** [comment]
Tested personally, could not make this move cause that. Must have been some other effect in play that produced the error. Still, I am glad you made the report because I did find other things in relation to this I want to change. If you have any other idea what may have dropped your AGI, please continue to post to this issue, I'll still see it.

**Comment by TeoTwawki** [comment]
ok wtf, retesting, a minuet after I despawned it..them my AGI shows whacked.

**Comment by TeoTwawki** [comment]
Ok found it, its Darkstar's end and I'll go fix that. Meanwhile LegionDark has received a hotfix till its next maint so this shouldn't a problem anymore.

**Comment by TeoTwawki** [comment]
P.S.
Non voidwatch Matids now no longer mistakenly use the voidwatch version of that special attack.
(that was the "other things" I mentioned)

**Comment by Walkersauce** [comment]
Thanks TEO!!!
