### ISSUE TITLE
63/80 inventory first ever Chaac Belt dropped to the floor.  Please help?  Posted in wrong area first.

### ISSUE THREAD

**Issue by slaggyt** [LegionDark/Issues#1358]
+Date & Time:2017-02-06  
+
+FFXI Client Version (use /ver):30161227_1
+
+Server's Expected Client Version matches, yes/no? (use $ecv):
+
+Character Name:Puuurl
+
+Nation:Bastok
+
+Job(level)/Sub Job(level):THF/DNC
+
+NPC or Monster or item Name:Nuhn , Chaac Belt
+
+Zone name: Arrapago Reef 
+
+Coordinates (use $where):Nuhn 
+
+ffxiah.com link (for items issues only):Nuhn ??? tele dem out already
+
+Multi-boxing? (multiple clients on same connection):yes
+
+Steps To Reproduce / any other info: Been farming all day Inventory was 63/80 al items wnt to the toons but the belt I do not have and lotted for dropped to floor.
+Took a screen shot but how do I post it here?  Please help.  Only fought Nuhn in the zone because i nexus capped to the pt leader.

**Comment by TeoTwawki** [comment]
+there are a way this can happen, like if you lot on it but one 
+
+or more characters doesn't pass it can be lost
+
+instead of fall to you because darkstar doesn't have that working like retail yet
+
+another way this can happen is what we call the "sort bug" 
+
+which is where your inventory client side has not been updated properly 
+
+and only issuing a manual command to "sort" will fix your inventory
+

Also, wtf did you do to my poor issue report template? it pre-fills the question text all you have to do is put answer on the blank lines. If you are on mobile or something and that doesn't happen for ANY reason, complain to github support FFS instead of slaughtering the poor innocent tracker. :cry:

**Comment by atom0s** [comment]
> in any case these are known issues for which policy is we don't restore loot pools

Closing because this is DSP's issue and not something we restore items for.
