### ISSUE TITLE
Ark Pentasphere - Unable to get in full moon

### ISSUE THREAD

**Issue by SolisFFXI** [LegionDark/Issues#1431]
**Date & Time**: 
Full Moon - 1800-0600

**FFXI Client Version (use `/ver`)**: 
30170304_01

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

yes
**Character Name**: 
Solis

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
PLD / RDM 99

**NPC or Monster or item Name**: 

Ark Pentasphere / Qu'Hau Spring
**Zone name**: 

**Coordinates (use `$where`)**: 
Ro'Maeve (H-6), x:0, Y:-29, Z:64 (193)

**ffxiah.com link (for items issues only)**: 

http://www.ffxiah.com/item/1550/ark-pentasphere
**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 

unable to trade ink / parchment to obtain item.

**Comment by Heepster03** [comment]
First, you must trigger the Divine Might quest:
To do this, you must be on or past Zilart Mission 14 - Ark Angels.

The Illuminink and Parchment must be traded to the Qu'Hau Spring found at (H-6) in Ro'Maeve (and traded from its southern platform; the target is out of range from the northern platform) when the spring is full of water, which only happens when the two following conditions are met:
The moon must be full.
The in-game time must be between 18:00 and 6:00.

Did you do this? ^

**Comment by SolisFFXI** [comment]
Yep, tried it for 2 in game nights, neither night worked.

**Comment by spectre99** [comment]
Also needs to be clear skies, can't be thundering or any other kind of weather effect.

**Comment by R3P0FFXI** [comment]
This works just fine, look on the forums there's a custom tweak for this
