### ISSUE TITLE
Not able to receive VW Chap4 Abyssites

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1465]
**Date & Time**: 5/6/17 -- 1:11am PST

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170304_1

**Character Name**: Raelious. Also reporting for Meokazi, Melious, Ripz, and Bombacloud

**Nation**: Raelious/Melious/Meokazi(Bastok) - Ripz/Bombacloud(Sandoria)

**Job(level)/Sub Job(level)**: Raelious BLU99/RDM49, Meokazi BLU99/RDM49, Melious RDM99/WHM49, Ripz BLU99/RDM49, Bombacloud BLU99/RDM49

**NPC or Monster or item Name**: n/a?

**Zone name**: n/a?

**Coordinates (use `$where`)**: n/a?

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: Just for Meokazi, Melious, and Raelious.

**Steps To Reproduce / any other info**: Reporting this for the listed 5 characters above. We have been progressing through Voidwatch and we're not recieveing upgrades to start Voidwatch Chapter 4 (Aht Urhgan or Tavnazia). For some reason when we killed all 3 of the NMs from ZIlart (Aello, Qilin, Uptala) our abyssite never reverted back to T1 it stayed on T3 for all of us. We have tried talking to every imaginable NPC related to VW, including Bulwark Gate in Saurmague_S, Verdical Confluxs in Pashh_S and Xarcabard_S, All 3 City Voidwatch Officers, the Door in RuLude, and Gilgamesh along with Keiran.

**Comment by TeoTwawki** [comment]
Tav's line (at Owain in safehold) looks for quest completion, not abyssite. I don't even recall if I ever fixed the ToAU line yet.

**Comment by TeoTwawki** [comment]
Chances are you guys didn't get your var set.

@LegionDark/gm `$checkvar <t> ZILART_VW` them for me?

**Comment by Heepster03** [comment]
- Raelious / Melious / Ripz all had ZILART_VW : 6

- Meokazi and Bombacloud weren't online but assuming the same. Will check when they are online.

**Comment by TeoTwawki** [comment]
that var stores a 3 bit mask of flags, so 111 binary = 7 decimal, and Qilin is bit 1, so they need to re-kill that NM. I have verified he's not coded wrong. Once they get Qilin's switch flipped their var will be 7, and the code to handle clearing that tier will activate.

**Comment by Raelious** [comment]
Ripz and I (Rae+Mel) both killed Qilin the evening before last thinking it was him but it still stayed the same. We farmed Uptala about 10 times, as well as Aello for chapters.

**Comment by TeoTwawki** [comment]
I stated wrong NM because I forgot this binding starts at zero instead of one (thanks darkstar..) so I stated the wrong NM name, but the details were otherwise correct.

I'm sorry, but we don't have any code bug here in the scripts. 

```lua
    if (player:hasKeyItem(ASHEN_STRATUM_ABYSSITE_III)) then
        if (player:getMaskBit(player:getVar("ZILART_VW"), 0) == false) then
            player:setMaskBit(player:getVar("ZILART_VW"),"ZILART_VW", true);
        end

        if (player:isMaskFull(player:getVar("ZILART_VW"), 3) == true) then
            player:completeQuest(OUTLANDS, SKYWARD_HO_VOIDWATCHER);
            player:addKeyItem(ASHEN_STRATUM_ABYSSITE);
            player:delKeyItem(ASHEN_STRATUM_ABYSSITE_III);
        end
    end
```
All 3 NMs are scripted identically except for checking and setting a different single bit of the mask: aeollo=0 qilin=1 uptala=2 (bit0+bit1+bit2=3 bits)

Fully log out so your sessions are cleared. Wait a minute or 3, log back ona  single character. If multiple peopel us eteh same internet connection, only one of you log in. Kill the thing again. If your group needs help because not all members coudl log in, ask the global LS for warm bodies to throw at it. I', telling you there is no code error on the servers end here, the only cause for that variable to not set is the crappy darkstar session handling that we cannot do anything to prevent. Variable 6 = 011 binary, means you don't have the ~~Qilin~~ Aello  bit set. If I manually set variables for everyone that has a party of multiboxers I'll never have time to handle anything else (would like to slap the guys who multibox in more than 6 alts then complain of lag in LS).

if its any consolation, when I have more time I'm getting rid of the entire key item cycling thing anyway. So eventually you'll simply keep them all forever.

**Comment by Raelious** [comment]
I'll go ahead and go solo Aello in about 30 minutes and report back.

Also semi-unrelated: When you finish the new updated VW and we keep our say White Stratum Abysite T6, would we also be able to pop any previous NMs in that tier, say anything n Jueno T2?

**Comment by TeoTwawki** [comment]
Yeah you guys will be able to pop any tier up to the tier you've cleared because you'll keep the previous tiers abyssites.

**Comment by Raelious** [comment]
Just killed Aello, still have Ashen Stratum Abyssite III

**Comment by Heepster03** [comment]
Just checked and Raelious still has ZILART_VW 6.

**Comment by atom0s** [comment]
There is a bug in Aello's script.

```lua
player:setMaskBit(player:getVar("ZILART_VW"),"ZILART_VW", true);
```

There is a missing param before true, which should be 0.

**Comment by atom0s** [comment]
Bug is fixed, tested and is working again.

**Comment by TeoTwawki** [comment]
No such bug existed in my copy so who's been ducking with live. Assclowns making me look bad.

**Comment by TeoTwawki** [comment]
God damn it

**Comment by TeoTwawki** [comment]
@Raelious I apologize I was sure I had run through this solo

@atom0s thank you dunno how I missed that
