### ISSUE TITLE
Sandworms have no model (prevents glavoid)

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1474]
**Date & Time**: 
May 11, 2017 - 11:12 PM MST

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Tbone

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 
Minhocao
Vermes Carnium

**Zone name**: 
Abby Tahrongi Canyon

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
The sandworms are invisible (missing model?).  Show up in widescan and minimap.

Glavoid has a model, but since Minhocao doesnt, he can't be killed making glavoid unpoppable.

**Comment by Jessland86** [comment]
Minhocao is also currently broken and does not spawn period. If you look it up on the monster tool it gives you an error. It also does not show up on widescan. The others can be killed by dragging things over to the area and -againg them. They do take damage,but since they have no models they cannot be directly targeted.

**Comment by TeoTwawki** [comment]
Just fixed both in DSP, will have a mini-main't soon to get legion up to speed
