### ISSUE TITLE
Lightreaver killing NMs

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1514]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Raelious

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99THF/49WAR

**NPC or Monster or item Name**: Odin, Alexander, Ravenous Crackclaw (Other custom mobs not yet tested)

**Zone name**: Hazhalm/Bibiki Bay

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Equip Lightreaver 99WAR axe, fight the aforementioned monsters and watch it instantly kill them, given it procs. It shouldn't proc on any "Notorious Monster" yet it does on these specific monsters, I havent yet checked the other custom mobs or witnessed it happening. But Im sure it might if it works on these 3.

**Comment by TeoTwawki** [comment]
The code we have already checks for NMs, so the onlyw ay I cans ee this happening is:

**A)** the server thinks that mob is not an NM (there is a flag that sets this per mob, which could be missing on specific mobs). If the NM does *not* check "impossible to gauge" the flag is definitely missing.

**B)** the server thinks this entity is not even a mob at all, in which case it should be crashing since you aren't allowed to attack NPC's or Players, but I'm not ruling that out yet.

**Comment by TeoTwawki** [comment]
@LegionDark/gm The code we have already checks for NMs, so the only way I cans ee this happening is:

**A)** the server thinks that mob is not an NM (there is a flag that sets this per mob, which could be missing on specific mobs). If the NM does *not* check "impossible to gauge" the flag is definitely missing.

**B)** the server thinks this entity is not even a mob at all, in which case it should be crashing since you aren't allowed to attack NPC's or Players, but I'm not ruling that out yet.

**Comment by TeoTwawki** [comment]
@Raelious thank you for reporting this

**Comment by TeoTwawki** [comment]
@Raelious looks like just bad flags. Odin and Alex were not checking as NM. And we couldn't reproduce on the cracklaw NM - he resisted insta kill like he was supposed to.  If you spot any additional NMs you think have this prob be sure to `/check` them. If they don't check "impossible to gauge" report them here.

**Comment by TeoTwawki** [comment]
Leaving this open for a little while longer in case additional NMs are found to be flagged wrong.
