### ISSUE TITLE
Skeletor Server Transfer

### ISSUE THREAD

**Issue by Skeletor4424** [LegionDark/Issues#1553]
I had posted my server transfer application just prior to the forums being moved. I wanted to make sure it didn't get lost in the transfer stuff. It is still in the applications portion. Just submitting a ticket to ensure the notification that someone had posted in that section didn't get lost when the forums were moved.

Thanks a bunch!

**Date & Time**: 7-6-2017

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Skeletor

**Nation**: Sandy

**Job(level)/Sub Job(level)**: Hoping to get them Transfered^^

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Iminiillusions** [comment]
Forum move hasn't happened yet, the DB with all the data of different posts will be dumped again. Nothing lost :).

**Comment by Skeletor4424** [comment]
Gotcha, does that mean the transfer stuff won't happen till after the offical forum move?

**Comment by Iminiillusions** [comment]
Most likely. The admins are busy getting stuff ready, and even then, it will take them time to go through all the transfer apps. I'd give it till a week or two after the migration. In the meantime, I suggest starting a brand new character to work on (it can't be the placeholder for your transfer, otherwise the transfer work) and see how far you get. Also, if you're in the discord, you'll find out more info on the migration :). If you aren't, you  can join using this code https://discord.gg/TKCMTN7.

**Comment by Skeletor4424** [comment]
Roger that, thanks for the info^^ I look forward to playing soon!

**Comment by Iminiillusions** [comment]
No problem

**Comment by TeoTwawki** [comment]
yes all transfers on hold for now. and i have been watching what happens to ensure  o posys get lost. even of that were to happen just repaot or let is know.

closing this, but you may post here if you have a related question or better yet, just hit us up in discord!
