### ISSUE TITLE
Certain TP moves causing death related symptoms

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1603]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: Buhkis, Achuka, Darrcuiln, etc

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Buhkis - Ruinous Scythe: Deals damage in a quadruple attack to targetted player in range. Additional effect: Max HP Down. 

Achuka - Incinerating Lahar: Only utilized at low HP: AoE magical damage and Weakness (despite the animation, this attack is neither conal nor fire-based).

Darrcuiln - Starward Yowl: (cant find a description on what this move actually does, sorry)

These are just some of the tp moves I can recall off the top of my head that cause a "Weakness" or "Max HP down" effect during a tp move. All moves show in the log of only doing lets say avg of 700-1400 dmg yet will pretty much just kill you anyway. (All tp move descriptions were found on BG-wiki, or FFXIclopedia)

**Comment by w3genesis** [comment]
Certain death for taru... just a tickle for galka :D
Be reborn bigger next time my son!
/jk maybe

**Comment by Raelious** [comment]
Its not really regarding race, these moves are putting Weakness/HP Down on players first then doing damage. Should be doing damage THEN putting on Weakness/HP Down.

**Comment by w3genesis** [comment]
That's true. And curor buffs should overwrite hp down effect, but doesn't do that here.

**Comment by TeoTwawki** [comment]
Cruor buffs I did in DSP ages ago, and probably did it wrong but as close as I thought I could at the time - they behave differently than the standard stat boost form other sources, so I just made a "dummy" effect for them. They probably need to use the 2nd tier (which DSP didn't have in its effect ID's list at the time) with different handling to prevent them being overwritten.

..I think retail actually removes them after zoning instead of on zone as well. I have a screenshot with my chatlog being bombed with the wear off message after teleporting out of abyssea. Doubt anyone cares about the order though, just musing on how SE did it.

Does any move on retail do weakness ***and*** damage in the same attack? I think that's probably custom things gone ~~wild~~ wrong but I'll check each move named that does it.

**Comment by Raelious** [comment]
Incinerating Lahar, Riptide Enertia, Rending Delude all put weakness on a player.

**Comment by Jessland86** [comment]
I previously reported the Bukhis thing here: https://github.com/LegionDark/Issues/issues/1383

**Comment by Rihyuh** [comment]
So the Ravenous Crackclaw shouldnt be doing 2 moves that cause weakness for 1min????
If so, we left that thing alone after that crap

**Comment by Raelious** [comment]
@Rihyuh no shouldn't be, and the weakness lasts anywhere from 30seconds to nearly 2minutes.

**Comment by Rihyuh** [comment]
Thank the Lord above. I was destroying my brain with ways of dealing with fighting that thing and its use of weakness moves.

**Comment by TeoTwawki** [comment]
I need to fix the cruor buffs in darkstar, but the rest should be all good after maint.
