### ISSUE TITLE
Rescue Drill Mission Issue

### ISSUE THREAD

**Issue by LilithMeredy84** [LegionDark/Issues#1676]
**Date & Time**:  7:53am  November 26th, 2017

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: no

**Character Name**: Ayano

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: Thief 15

**NPC or Monster or item Name**: Tayula

**Zone name**: La Theine Plateau

**Coordinates (use `!where`)**: (F-7) X; -292 Y: 28 Z: 144

**ffxiah.com link (for items issues only)**: Not an item issue

**Multi-boxing? (multiple clients on same connection)**: not dual boxing

**Steps To Reproduce / any other info**: Issues with Sandy Mission 2-1 Rescue Drill, Speaking with NPC Tayula causes the mission to become bugged and the dialogue to freeze and not cotninue.

**Comment by EpicTaru** [comment]
Please go in game and type /ver. Your client version number is important for us to determine a cause.

**Comment by EpicTaru** [comment]
@LilithMeredy84 Updated your ticket with your client version.  Your issue is due to a client version mismatch.  You'll run into other issues interacting with NPCs and CSes related to the client version mismatch.  Nothing that anyone can do regarding client version mismatches until the version update maintenance of the server occurs.  No set ETA for when the version update maintenance occurs so please just continue being patient. Thanks kindly in advance. :)

**Comment by R3P0FFXI** [comment]
Duplicate ticket which will be resolved next time we update closing issue
