### ISSUE TITLE
'Quaratine' player -jail issue

### ISSUE THREAD

**Issue by Im-Mortal** [LegionDark/Issues#1686]
**Date & Time**: 
12/3/17

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
i dont know

**Character Name**: 
Quaratine

**Nation**: 
windurst?

**Job(level)/Sub Job(level)**: 
eighty somthing bluemage think subbed dancer

**NPC or Monster or item Name**: 
baist killed me

**Zone name**: 
Xarcabard

**Coordinates (use `!where`)**: 
?

**ffxiah.com link (for items issues only)**: 
X

**Multi-boxing? (multiple clients on same connection)**: 
was but seems unrelated

**Steps To Reproduce / any other info**: 
jailed upon trying to homepoint

**Comment by Im-Mortal** [comment]
![ffxi_2017 12 03_14 27 38](https://user-images.githubusercontent.com/24876050/33529083-8147ef6a-d839-11e7-80a4-e9b2fbbf3550.png)
![ffxi_2017 12 03_14 27 40](https://user-images.githubusercontent.com/24876050/33529084-8151fafa-d839-11e7-965b-25a383ba60db.png)

**Comment by R3P0FFXI** [comment]
@Im-Mortal this isnt an issue this is working as intended because your macro probably tries to remove the weakness buff using the debuff plugin.

**Comment by TeoTwawki** [comment]
The server detected an attempt to strip non removable status effects. This check has been thoroughly tested and does not fire off from:
weakness wearing off
homepointing
raise/reraise
attempts to use the mouse/keyboard to click off status icons

Only use of an addon to remove an effect you otherwise could not, would have done this. And the entire process of it was recorded.

Please ensure you have disabled any windower or ashita scripts or macros that would attempt to automatically remove such effects (like weakness) so that you don't auto-jail yourself again, and I will release you at my earliest convenience. Consider it a slap on the wrist. 

anyone not believing me I'd be happy to show you video footage of every variation of it. I prepared for exactly this situation.

**Comment by Im-Mortal** [comment]
Wierd, thanks for the info and sorry about that.

**Comment by TeoTwawki** [comment]
Player released
