### ISSUE TITLE
Cleavage- in the Quarantine room

### ISSUE THREAD

**Issue by Skeletor4424** [LegionDark/Issues#1687]
**Date & Time**: 
6:25PM CST 12-3-2017

**FFXI Client Version (use `/ver`)**: 
Just updated to newest version

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
Yes

**Character Name**: 
Cleavage

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99PLD/49WAR

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Only had 2 on atm

**Steps To Reproduce / any other info**: 
I updated the client to the new version as per the post. Logged into the server and it came up in mordion quarantine and kept zoning me in, again and again. I logged out turned off all addons/plugins and logged back in. Seems to stay connected now. the NPC said to contact a GM, so here I am.

**Comment by Skeletor4424** [comment]
Going to go get some dinner, be back shortly.

**Comment by Skeletor4424** [comment]
Back.

**Comment by TeoTwawki** [comment]
This happens from using tools or addons that try to strip off status effects that you normally cannot.

Each time that happens the code will re-jail. Even if you are already in jail. Please disable any such tools and remove them and any windower or ashita scripts or macros that would attempt to automatically remove such effects (like weakness) so that you don't auto-jail yourself again, and I will release you at my earliest convenience. And hopefully I never see you jail yourself again.

**Comment by Skeletor4424** [comment]
Gotcha, all plugins/addons are disabled on me atm

**Comment by TeoTwawki** [comment]
If you are an ashita person I think the addon is called debuff, you want to avoid using that to remove things like weakness and anything automating that. Basically if you coudln't click it off with your mouse/keyboard/controller then you don't want debuff trying to remove it either.

**Comment by Skeletor4424** [comment]
Roger

**Comment by TeoTwawki** [comment]
I'll be hanging around in mordion for a bit, if I miss you when you are on tag me in discord

**Comment by TeoTwawki** [comment]
released player
