### ISSUE TITLE
Neomorpheus - In Mordion Gaol

### ISSUE THREAD

**Issue by neoffxi** [LegionDark/Issues#1692]
**Date & Time**:  12/03/2017 12:45AM EST

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: yes (3017110*)

**Character Name**: Neomorpheus, Neommule, Neofour

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Pld99/War99, Whm99/Rdm49, Whm99/Rdm99

**NPC or Monster or item Name**: n/a

**Zone name**: Mordion Gaol

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: Yes, 3 characters at the moment

**Steps To Reproduce / any other info**: 
Concurrently, I logged in my main character and 2 mules (Neommule and Neofour) after the server maintenance in Bastok Mines, and was sent to jail. I was told it is probably because of the cancel plugin; I have removed the addon since then.

**Comment by R3P0FFXI** [comment]
@neoffxi this is due to you attempting to cancel stats effects which cannot or should not be cancelled

**Comment by TeoTwawki** [comment]
***gernic copy pasta reply:****
This happens from using tools or addons that try to strip off status effects that you normally cannot.

Each time that happens the code will re-jail. Even if you are already in jail. Please disable any such tools and remove them and any windower or ashita scripts or macros that would attempt to automatically remove such effects (like weakness) so that you don't auto-jail yourself again, and I will release you at my earliest convenience. And hopefully I never see you jail yourself again.

**Comment by neoffxi** [comment]
Thank you.

Also, the addon has been removed.

**Comment by TeoTwawki** [comment]
I just missed you in mord if you wanna log back in

**Comment by neoffxi** [comment]
Logging back in my characters now.

**Comment by neoffxi** [comment]
Thank you.

**Comment by TeoTwawki** [comment]
released player + alts
