### ISSUE TITLE
My characters stuck in Mordion

### ISSUE THREAD

**Issue by Rihyuh** [LegionDark/Issues#1693]
**Date & Time**: 
12/04/2017 9:00 am

**FFXI Client Version (use `/ver`)**: 
Was the old version, but has newest version as per the post

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
Furrow, Rihyuh, Raynee, Boyahdabum

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
99 BLU/49RDM, 99BLU/49RDM, 99BRD/49RDM, 99WHM/49RDM

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
YES

**Steps To Reproduce / any other info**: 
![screenshot1](https://user-images.githubusercontent.com/24214123/33562337-4c2635e6-d8d2-11e7-8149-6cb4fb93410a.png)
![screenshot2](https://user-images.githubusercontent.com/24214123/33562338-4c3f1f52-d8d2-11e7-947c-158df1c02c60.png)

**Comment by R3P0FFXI** [comment]
@Rihyuh this is due to you attempting to cancel status effects which cannot or should not be cancelled.

**Comment by Rihyuh** [comment]
Ok.......I gave you my SS of what I was doing before I got jailed. 
I was trying to learn a BLU spell with my wife in a low lvl area with 8 lvl 99 characters. Please tell me what I needed to remove getting barbed Cresent from a mob I can kill with a couple hits by myself.

Can I be shown some proof please of what I did?
It pretty much ruined my whole day of playing and all that happens was ppl acting rude instead of actually trying to help.

**Comment by R3P0FFXI** [comment]
@Rihyuh First off dont be a dick. I told you what you did your using Cancel to try and cancel a status effect that cannot be cancelled. This was a previously big exploit on the server we have since fixed the loophole. This has been tested multiple times and is only triggered when you attempt to cancel an effect which should not be cancelled. This is cheating anyway you look at it. I dont know which effect you were attempting to remove just that it was one which should not be removed.

**Comment by Rihyuh** [comment]
Me being a dick? Seriously, thats all i got yesterday when i tried to get
help.

At this point, i gave you what you asked for and you have given me no proof
of me doing anything.
Unless your system is perfect, i was spamming dia and mind blast during the
mega lag yesterday and got ported out, all 4 of my toons.

This is the 2nd time i have been playing and had issues.

I recall your GM Raina and Souless accusing us of doing something with no
proof.....and we had a video showing we did nothing.

I gave you my screen shots showing i was doing what i said. Can i have
yours showing me doing what you are accusing me of? Or is it too much to
admit your server isnt running top notch recentlt and shit might be a
little off?
Or is using Cure please a jailable offense beings it jailed someone too..

I tried being civil and nice the other day, but all i see is you getting
personsl enjoyment out of anyone having a bad time due to your server.
And you want lots of unique characters on your server?

If you have proof to keep me in jail, please show me, if not, can i please
go back to learning BLU spells?

On Dec 4, 2017 9:49 AM, "R3P0FFXI" <notifications@github.com> wrote:

@Rihyuh <https://github.com/rihyuh> First off dont be a dick. I told you
what you did your using Cancel to try and cancel a status effect that
cannot be cancelled. This was a previously big exploit on the server we
have since fixed the loophole. This has been tested multiple times and is
only triggered when you attempt to cancel an effect which should not be
cancelled. This is cheating anyway you look at it. I dont know which effect
you were attempting to remove just that it was one which should not be
removed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LegionDark/Issues/issues/1693#issuecomment-349023945>,
or mute the thread

**Comment by EpicTaru** [comment]
@Rihyuh dude, please, just sit tight and be patient. I told you we'd talk in a couple hours.

**Comment by TeoTwawki** [comment]
Let me just explains how this works:

The server detected an attempt to strip non removable status effects. This check has been thoroughly tested and does **not** fire off from:
weakness wearing off
homepointing
raise/reraise
attempts to use the mouse/keyboard to click off status icons

This **only** happens from using tools or addons that try to strip off status effects that you normally cannot. This doesn't check if you had the effect, only that you attempted to remove one that you aren't supposed to be able to. Each time that happens the code will re-jail. Even if you are already in jail. Please disable any such tools and remove them from any windower or ashita scripts or macros that would attempt to automatically remove such effects (like weakness) so that you don't auto-jail yourself again. First time auto jail = slap on wrist, It is not productive to fight about it you only dig yourself a hole and accomplish nothing. There is zero chance of a false positive, if you'd like to watch me demonstrate it that can be arranged later.

**Comment by Rihyuh** [comment]
I fully understand how the system works.
I do appreciate a civil response as i am not trying to fight or argue about
anything.

All i am stating is i disclosed my actions and its a my word vs yours. Im
not trying to do anything but get past getting told i was doing something
when i wasnt....and not be told im guilty with no proof.
I think thats fair on my side to ask for a neutral approach bc ive been
accused before on this debuff issue and the GM was wrong.....we showed
video proof and never recieved an apology or anything.

I have already combed my auto load list to avoid anything from hopefully
happening again.

Hopefully this makes sense, im trying to be nice and do all i was asked to
do, not be told a robot or program told me i did something wrong and works
100% flawlessly without a possibility of an error anywhere in the
system......bc the way the server was acting and still is acting, its very
obvious nothing in the system currently is 100% and flawless.

Sorry if you feel im tryng to fight or anything other than be heard and
discuss my situation with those than "can" and are willing to help. Its how
a good server would be ran, or anything for that matter.

**Comment by TeoTwawki** [comment]
> All i am stating is i disclosed my actions and its a my word vs yours. 

This is not the case. I really is not. That code triggers only under very explicit circumstances

**Comment by TeoTwawki** [comment]
RE: previous incident
Gm staff involved were told they shouldn't have spoken because no investigating on the admin back-end had been preformed prior, and even suggesting something may have occurred provokes players.

This time around, i coded the back end to automatically throw players into mordion when impossible situations happened. There is no way to trigger this by accident. I tested this *my freakin self* in every possible way.

**Comment by Rihyuh** [comment]
Honestly, i know what i did and didnt do.

Its very obvious neither of us are getting anything ptoductive done here.

When programs work 100% perfect, ill believe you.....until then, ive
already heard the system has put ppl in mordion for using cure please and
cleavage for not having an update. So tell me again, did any of your tests
show that?
If they didn't, then why did it happen?

Its easy to call someone a liar, its really shityy to continue to do it
without proof.

**Comment by TeoTwawki** [comment]
Yeah you can stay there now. I know exactly what occurred. You aren't going to be allowed to just keep denying the truth when I do have teh proof and no I don't have to show it to you - retail wouldn't show you either. I have your incoming packet to the server and that is enough for me to say without even a  shadow of a doubt what transpired. Our GMs were getting pretty frazzled, and coudln't definitely prove anything before..So I automated it - now there is zero doubt. Enough is enough, If you want to quit over it be my guest otherwise there is nothing further to discuss here.

@LegionDark/gm 72hr minimum. Everyone else continues to get release as soon as they confirm they have removed the exploitative addon command on their 1st offense, normal policies apply on any re-jailings.

**Comment by R3P0FFXI** [comment]
@TeoTwawki Locking and closing ticket im tired of this crap

**Comment by TeoTwawki** [comment]
@LegionDark/gm  vid.me is shutting down looking for someplace else that isn't youtube to upload the video footage of the auto-jail tests discord me any recommendations
