### ISSUE TITLE
im in jail for not thinking about debuff use :)

### ISSUE THREAD

**Issue by Nobitso** [LegionDark/Issues#1695]
**Date & Time**: 12/4/2017 5:19pm

**FFXI Client Version (use `/ver`)**: version 30170427_0

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: no

**Character Name**: Nobitso

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: 

**Zone name**: South sandy now in jail
![nobitso_2017 02 12_161239](https://user-images.githubusercontent.com/34253302/33579505-0820328e-d918-11e7-8e3a-30c0f2390a41.png)
![nobitso_2017 12 04_163505](https://user-images.githubusercontent.com/34253302/33579506-0845c49a-d918-11e7-9a5e-990bc7eb5370.png)
![nobitso_2017 12 04_163517](https://user-images.githubusercontent.com/34253302/33579507-08680168-d918-11e7-9b49-4cb729c5360c.png)
![nobitso_2017 12 04_163522](https://user-images.githubusercontent.com/34253302/33579508-088ed018-d918-11e7-8401-b39d08124d92.png)

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by TeoTwawki** [comment]
_**generic copy paste reply:**_
This happens from using tools or addons that try to strip off status effects that you normally cannot.

Each time that happens the code will re-jail. Even if you are already in jail. Please disable any such tools and remove them and any windower or ashita scripts or macros that would attempt to automatically remove such effects (like weakness) so that you don't auto-jail yourself again, and I will release you at my earliest convenience. And hopefully I never see you jail yourself again.

**Comment by TeoTwawki** [comment]
released player
