### ISSUE TITLE
Changing to PUP crashes the server

### ISSUE THREAD

**Issue by piglorian** [LegionDark/Issues#1712]
**Date & Time**: 
12/8/17 9:57 CST

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes

**Character Name**: 
Piglorian

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
99PLD/49WAR

**NPC or Monster or item Name**: 
Nomad Moogle

**Zone name**: 
Nashmau

**Coordinates (use `!where`)**: 
x:9 y:-6 z:31 (149)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Changed job from PLD/WAR to PUP/WAR at a Nomad Moogle and the server crashed.  I did this twice, not thinking that this was the cause of the first crash.

**Comment by TeoTwawki** [comment]
Confirmed with details:

part of the automaton data is not being unloaded so when you job change BACK to pup after having been another job for awhile, it explodes trying to finalize the stats of the automaton you don't actually have in town. for some reason only at nomad mogs. So the actual cause is when you change FROM pup, but the crash happens later when changing TO pup. :scream:


**Bug is avoided by dismissing automaton before changing off of pup.** Also doesn't trip unless in certain gear that modifies the automatons stats.

**Comment by piglorian** [comment]
Additional info: I unlocked PUP tonight and never summoned the automation.  I did happen to change to PUP once while in town and it worked once, but then I changed to THF to farm attachments.  After that I tried changing to PUP in my Mog House and it crashed again.

**Comment by TeoTwawki** [comment]
did you ever equip anything that midified auto stats, like an itemlevel enhanced animator?

cant see why dismiss is preventing the crash honestly

**Comment by piglorian** [comment]
Never equipped anything.  The one time I was able to change to it, the only thing I did was to talk to the attachment NPC so that I would be able to turn them in.  I turned in the all of the purchased attachments that I had and then went and farmed others I was missing.

**Comment by TeoTwawki** [comment]
@Jessland86 /stumped

**Comment by TeoTwawki** [comment]
I got it fixed will update soon
