### ISSUE TITLE
Dhorme Khimaira and Upas-Kamuy drop is 1% use TH 10

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#179]
Date & Time: 07/23/2015 9:11am
Frequency: always
FFXI Client Version:30150619_2
Character Name: Cassy
Race: hume
Main Job: Thf
Sub Job: Dnc
Area & Coordinates: Abyssea - Uleguerand
Party or Solo: party
NPC Name: 
Monster Name: -
Multi-boxing? (multiple clients on same connection): Yes
Steps To Reproduce The Issue:I took two weeks killing these NM , + - 10 hours a day playing gotten four e Savant 's Seal : Body , 3 Bale Seal : Body , Core does not fall Snow God never drop is 1% , help please

**Comment by R3P0FFXI** [comment]
Have you looked at what the mob drops?

3130	Ravagers Seal Body	10.00%
3137	Bale Seal Body	10.00%
3145	Mavi Seal Body	10.00%
3149	Savants Seal Body	10.00%
11901	Tropic Gages	10.00%
28402	Asperity Necklace	15.00%
19402	Ukonvasara	34.00%

Core is not even listed as a drop from Dhorme Khimaira

3156	Creed Seal Hands	10.00%
3159	Aoidos Seal Hands	10.00%
3160	Sylvan Seal Hands	10.00%
3165	Mavi Seal Hands	10.00%
3246	Snow God Core	10.00%
15910	Primal Belt	10.00%

Upas Kamuy drop is 10% for core not 1% so not sure what the issue is

10% means it has a 10% chance of dropping each time you kill not 10% total.

**Comment by nekrol** [comment]
I always look the drop rate equal to not fall another 10 % from other abys , is a comparison to 1 %

**Comment by R3P0FFXI** [comment]
This is working as intended, however we will keep an eye on drops and see if maybe something changed in DSP.
