### ISSUE TITLE
Random R0s

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#180]
All day ive been receiving R0s at different times in different areas. After a brief wait (around 5-10 mins) I attempt to relog in only to be greeted by multiple POL or server errors. POL0001/0033/0044 
"Cannot connect to world server" and being stuck at the "Downloading data" screen.

Estimated login takes around 1hr from point of 1st disconnect

**Comment by puffer1221** [comment]
im actually getting the same issue as well, not too sure whats happened but it seems to keep us logged in even though we r0`d

**Comment by R3P0FFXI** [comment]
We are aware of the issues and are working on it. DSP forced us to update to Visual Studio 2015 which killed our auto restart option. Currently I am babysitting the server to manually restart it when it crashes. Until we can get the auto re-starter working properly with Vs 2015 there is nothing we can do to stop the issues.

**Comment by TeoTwawki** [comment]
Both the crashes from ranged attacks should be fixed and the packet flood dc'ing in dyna should be either fixed or at least less likely after next maint. Still a crashbug involving people crossing over to another map server that seems to be related to multi boxing that we can't do anything about yet.

**Comment by TeoTwawki** [comment]
What I suspect is happening:
Player A has 3 character online, 2 are inside Abyssea. 3rd character zones into Abyssea...Abyssea server crashes. All 3 character log back in, all 3 are in Abyssea. 2 zone out. 3rd zones out and main map server crashes. The crash dump info seems to indicate the server confused the current zone and destination zone, and tried to deal with wrong zone+wrong map server combination causing the crash because Abyssea zones and the zones you enter it from are not on the same map server. 

The same thing is happening with Dynamis, BCNM, Legion, and when we had allowed people to use it, the GM monster test zone.

**Comment by TeoTwawki** [comment]
This is mostly fixed now, only thing left are recurring crashes we have open issues with DSP for that have been ongoing for over a month (null zone and alliance bugs) so I am closing this out now.
