### ISSUE TITLE
Mailed some gil

### ISSUE THREAD

**Issue by jazzy00** [LegionDark/Issues#204]
Sorry to be a bother. Mailed myself some gil from an alt named Mew to my main named Jazzy. Sent 1 mil then sent 200k. It's gone from the Mew's mailbox but never showed up for Jazzy. 

**Date & Time**: Aug 3, 2015 aprox 7:00pm 
**Frequency**:
**FFXI Client Version**: Ver  20150629_4
**Character Name**: Jazzy
**Race**: Hume
**Nation**:Sandy 
**Main Job**:99 whm 
**Sub Job**: Smn
**Area & Coordinates**: South Sandy
**Party or Solo**:solo
**NPC Name**: moogle mailbox
**Monster Name**: NA
**Multi-boxing? (multiple clients on same connection)**: Yes. Mailed the money from Mew and then logged her out. 
**Steps To Reproduce The Issue**:

**Comment by TeoTwawki** [comment]
"Sent 1 mil then sent 200k" Clarify that statement. You can't send multiple different amounts of gil...

**Comment by jazzy00** [comment]
It showed that the 1 mil was gone and then I sent another 200k since you can only send 1 mil at a time. and when I went to check none of the money was in Jazzy's mailbox.

**Comment by TeoTwawki** [comment]
Did you mail anything else at all even to any other characters around this time? was the gil the ONLY thing in the send box? Because you are normally not even able to send another gil amount until after the first is picked up - the game doesn't "disappear" it and let you send another batch until its been picked up but there is a well known bug where the wrong slots are opened back up when multiple items are in the send queue.

**Comment by jazzy00** [comment]
I thought that was strange. I went to my mog house on Jazzy to check the mail and there was nothing. so I went back onto Mew's account and the gil was no longe there But it did let me put 1mil in the first slot and 200k in the 2nd slot when I went back to mew the money left the delivery box like it normally does when an item is received. Honestly not worried about the gil since it's pretty easy to make. I just wanted to fill out the bug report because I was asked to :)

**Comment by TeoTwawki** [comment]
Its been an exceptional bad day for me or I'd have gotten more done on investigating this. When I get back tomorrow going to sift the database to see if the amounts are still lost in the delivery or send queue, hopefully we can figure out exactly what happened and how before it happens to someone again. 

If you have anything in any characters send box or delivery box, please check all characters delivery box and make sure that is empty at the moogle. And sorry to ask this but if you can not add anything new to the send box till I check the queue that will help me (its holds limited amount of info at once and I don't want to sift the older db data if I can help it).

**Thank you for all the information thus far and I will update this when I can.**

Also of note: there is a largely cosmetic known issue where sending items to multiple recipients can result in invalid send box display. This usually manifest on the senders ends as "stuck slots" where attempting to send results in the congestion message, and visibly the wrong slots appear to have been emptied. The characters receive the correct items though. At this time I do not think this is related but wanted anyone reading the issue here to know that there are (multiple) known bugs with the mail system.

**Comment by jazzy00** [comment]
It's ok I understand :) I just checked both Jazzy and Mew's out and inboxes and neither have anything. I have not mailed anything from Mew since then. Jazzy has received items in Dbox from ah payments. I did put the money in the first and second slots (I should know from other servers the 1st box is wonkie but didn't think about it). I'm wondering if it's a bug with Jazzy seeing how I have another report open with 60% whm spells all gone, all blm, rdm, and smn spells are gone :( Opened that one yesterday. Maybe I should just another toon lol

**Comment by TeoTwawki** [comment]
@jazzy00  couldn't find the record, AH sales gil had already overwritten the current data and the older data was unreadable due to a screw up on our part. ..So its safe to do whatever you needs with your deliv box now (barring future glitches). We'll get you the 1.2mil back soon as a GM can get with you I'm just SOL on trying to figure the bug out for now.

**Comment by TeoTwawki** [comment]
(if someone hasn't already when staff was discussing the bug)

**Comment by jazzy00** [comment]
Not to worried about it. But ty for looking into it at least. :)

**Comment by Kaoriasada** [comment]
Contact Halsey when you're in-game and I can give you the lost gil.

**Comment by Kaoriasada** [comment]
Jazzy's gil was recovered.
