### ISSUE TITLE
Sandy mission 9-2

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#23]
**Date & Time**: 1:20 PM est
**Frequency**: Anythime I zone to North Sandy
**FFXi Client Version**:30150508_8
**Character Name**:Baucant and Dapunted
**Race**: Elvaan, Taru
**Main Job**:Thf,   Whm
**Sub Job**:Dnc,  Rdm
**Area & Coordinates (Type @where to get this info.)**:N. Sandy X:0 y:0 Z:-30 (189)
**Party or Solo**: Party
**NPC Name**: n/a
**Monster Name**: n/a
**Steps To Reproduce The Issue**:
http://ffxiclopedia.wikia.com/wiki/The_Heir_to_the_Light
Finished fight I recieved the cutscene after the fight but zoneing into North Sandy does not trigger cut scene to continue progression of this mission

**Comment by TeoTwawki** [comment]
Last few bits of nation missions are buggy in DSP.

**Comment by TeoTwawki** [comment]
Buggy and or **incomplete**, I should say. Some stuff just doesn't exist to be bugged yet.

This particular one has had several changes since being "implemented" (somebody did not test their stuff...) including changing the variable name altogether. So its likely you don;'t have the variable that would trigger that cs, will get with you in game to see if thats all you need.

**Comment by TeoTwawki** [comment]
set MissionStatus var to 4 (form 3) and next CS played. May have been the old dualbox variable glitch in action.
