### ISSUE TITLE
Lost dynamis currency 

### ISSUE THREAD

**Issue by unknownwolf** [LegionDark/Issues#239]
Date & Time: 15/08/15
Frequency: 1 time
FFXI Client Version: 30150619_2
Character Name: Volks
Race: Elvaan
Main Job: Thf
Support Job: Dnc
Area and Coordinates: Castle zvahl baileys J-8
Party or Solo: Solo
NPC Name: Switchstix
Monster Name:none
Steps:
1.Lost 1 ten thousand byne bill by trading it to npc Switchstix.
2.I had to trade the items to the??? point inside dynamis xarcabard.
3.
<Stage 4 > Stage 5
Wait Time: None
Added Bonus: 30 100 Byne Bills, M. Silverpieces, or L. Jadeshells
This last step requires two Rare/Ex drops from Dynamis: Xarcabard: a Shard of Necropsyche and a Fragment (which may prove difficult to obtain) specific to your Relic Weapon, as well as a single 10,000-unit Ancient Currency of a specific type. Once you have all these items, pay a visit to Switchstix yet again (Note: going to the goblin is optional). Upon talking to him, you will get a cutscene in which your Relic Weapon will speak to you. Now head out to the appropriate location (which can be found grouped with the Items Needed in the tables below) for your specific weapon to find a blank ???. Trade your Relic Weapon and the required items (including the Ancient Currency) to the blank ???. After a cutscene, you will receive your 5th stage, and completely upgraded, Relic Weapon! And as an added bonus, you will get back 3,000 of whatever Ancient Currency you had to trade for this final step..> 

BG Wiki link for additional information: http://ffxiclopedia.wikia.com/wiki/Category:Relic_Weapons

**Comment by R3P0FFXI** [comment]
First it is now impossible to trade just the 10k bill to Switchstix it was fixed by DSP several weeks ago. The only way what happened to you happened would be if you cancelled the trial and lost your relic. 

[11:28:57] <volks> Hey, I lost a 1 ten thousand to npc , is it possible to get it back?
[11:47:23] <Strafeous> Sorry, you need to read the prereqs and stuff and not try and trade items in and end up completely cancelling the relic
[11:47:38] <Strafeous> it's a clear message when it says you're cancelling it and you'll lose your mats
[11:47:38] <Strafeous> sorry
[11:49:01] <volks> I trade the currency by mistake

You admit here in IRC you screwed up.

[13:02:45] <volks> I will be waiting for a real GM to help 
[13:34:04] <volks> it'S so long to get answered
[13:40:18] <volks> I did really farm all that ammount of ccurency , I even have farm tanzanite jewel, i have 62 in total atm . I wouldnt lie to get free currency
[14:06:26] <volks> well you guys make it clear that you dont want to keep me on your server.

I and others will not stand for this type of abuse, MAYBE had you not been so condescending about it I would have considered a refund on a 1x basis. After seeing what you said to Strafeous in IRC there's no way in hell im even going to consider refunding this currency. It is clear you cancelled the trial which is why you lost your currency this is exactly as it is on retail and the exact response SE would give you. Here is your "Real GM" responding. 

Stay or go up to you the decision is final and non negotiable.

**Comment by TeoTwawki** [comment]
Not long after you had opened the 1st ticket I had been actually looking for you in game, was going to give you the currency back anyway..But then you acted like we take sooo long to handle tickets and then after that started getting mouthy with Straf and I didn't feel like talking to you after seeing those 2 things, so left it for the others to handle/decide on. And I stand by what they chose, now, after seeing everything that has happened.
