### ISSUE TITLE
AH selling for 1gil and buying back for more.

### ISSUE THREAD

**Issue by maeinit** [LegionDark/Issues#24]
**Date & Time**: 5/27/2015-5/28/2015 (Ongoing)
**Frequency**: Always? Still present
**FFXi Client Version**: 30150508_8
**Character Name**: Aishii
**Race**: Mithra
**Main Job**: WHM75
**Sub Job**: SCH37
**Area & Coordinates (Type @where to get this info.)**: Anywhere using @ah
**Party or Solo**: Both?
**NPC Name**: Auction House
**Monster Name**: N/A
**Steps To Reproduce The Issue**: @ah or click on auction windows, navigate normally view history and see AH-Bot is selling item for 1gil, BUT in the same list it shows AH-Bot buying back from players for 50,000 gil. You are able to buy it for 1gil.  Example: Mahatma cape (One I saw when I was cape shopping for WHM)

**Comment by TeoTwawki** [comment]
Just so you know: When the prices get adjusted in the bot's data files, the existing history on the Auction house is not automatically updated. In generally once enough new entries are created the old ones will drop off the history so nobody has been manually erasing the outdated history info.

Since you are telling us its buying for more than its selling though, that sounds like a price bug and will be addressed ASAP. Just be aware you'll still see that history afterwards.

**Comment by R3P0FFXI** [comment]
I have 2x test Mahatma capes on AH now, testing to see if it buys at regular or stack price.

**Comment by TeoTwawki** [comment]
@R3P0FFXI  That makes no sense - gear is not stackable at the AH

**Comment by R3P0FFXI** [comment]
Both capes were purchased by the bot for 50k bot appears working as normal
