### ISSUE TITLE
Kieran (Ashen stratus abyssite) crashing in cut scene.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#299]
Date & Time: 09/08/2015 (11:55pm)
 Frequency: Everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: Norg
 Party or Solo:
 NPC Name: Kieran
 Monster Name: 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: I'm getting crashed when i got "Ashen stratus abyssite" in finish cut scene...

**Comment by bathuka** [comment]
same pol crash

**Comment by R3P0FFXI** [comment]
Thanks guys we will look into it and let you know

**Comment by TeoTwawki** [comment]
@LegionDark/gm players that were effected by this should have received a quest "Voidwatch OPs Border Crossing" that would have allowed them to flag 2 additional quests (one in Rabao, 1 in Kazham), before fighting any monsters. Due to the bug players were given the key item without the quest being flagged and were able to fight the monsters without getting credit form a separate bug i am fixing as I type this.

**Comment by TeoTwawki** [comment]
Players who were with Loki Tonight can be fixed by:
`@addmission 5 100`
`@addmission 5 101`
`@addmission 5 102`
`@completemission 5 100`
`@completemission 5 101`
`@completemission 5 102`
Keiran will then function normally for those players.

**Comment by TeoTwawki** [comment]
Re-posting due to a mistake in my previous post...

Players who were with Loki tonight can be fixed by:
`@addmission 5 100`
`@addmission 5 101`
`@addmission 5 102`
`@completemission 5 101`
`@completemission 5 102`
Keiran will then function normally for those players.

**Comment by TeoTwawki** [comment]
All bugs I am aware of are now fixed.

**Comment by Dimmabr** [comment]
Teo, i am trying get ashen startus II, yesterday i was with Loki, Batman, Tarot, Zaya and Bathuka but, when i click on the NPC (Kiaran) he said to talk a voidwhatch officer but nothing happen when i try to talk his.

**Comment by R3P0FFXI** [comment]
Dimma because you need the mission fixes you need to read what Teo has posted a GM will get with you when we have time and run the necessary commands to fix your issues.

**Comment by Loki79** [comment]
@TeoTwawki not yet...  got everyone past it now but the other issue is NORG_VW_STATUS is not being set.  Once I set it manually they all progressed fine.  Ill update when I have a min to go through and find where that's being set at.

**Comment by Loki79** [comment]
ok looks like giglamesh is setting it so I'm guessing its an order of operation issue and they missed it being set from us adding and completing those quests.  Looks like it should be good for future players.  But if it comes up again that's where I would look.  @LegionDark/gm in addition the the add/complete quests listed above in some cases you may also need to @setplayervar "name" NORG_VW_STATUS 1

**Comment by TeoTwawki** [comment]
@Loki79 after having the rabao and kazham quests cleared talking to Kieran and then Gilgamesh should set that var naturally. I we also clear their border crossing quest it'll be missing, which was why I reposted because I shouldn't have said to clear that one by command line :x

I also was just alerted that I forgot to include target in the GM command examples I posted, so just edited that in...
`@command logID missionID target`
is how those work.

**Comment by TeoTwawki** [comment]
Anyone still having any problems will have to open a new issue, I know I fixed the *cause* of this one and I hope all those who were effected were taken care of by now so I am closing this.
