### ISSUE TITLE
T3cant up KI to T4

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#328]
Date & Time: 21/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: hiya
Race: Hume
Main Job:BLU
Sub Job: RDM
Area & Coordinates: none
Party or Solo:
NPC Name: Voidwatch officer
Monster Name:
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: HERE report
 
Kill 3NMs ask Voidwatch officer noting cant up KI to IV

**Comment by Loki79** [comment]
3 -> 4 is a quest.  Follow the quest progression please.

**Comment by qiganggang** [comment]
NO CS in voidwatch officer

**Comment by qiganggang** [comment]
![qq 20150921195143](https://cloud.githubusercontent.com/assets/13742980/9991172/41723b02-609a-11e5-8f06-756fc98cb5fd.jpg)

**Comment by Loki79** [comment]
Need to make sure they are receiving the alarum ki.  Only others who have progressed past this point I moved manually while we were fixing the NPCs.  I have a sneaky suspicion that's the case, as I had to add to the others.  I'm unable to do this atm but I'm sure Teo can get it set up for you when he has time.

**Comment by qiganggang** [comment]
This should not be my problem, right? I just do it in this job, but I can't do it, I can't do it.

**Comment by TeoTwawki** [comment]
I checked and you never had the preceding quest flagged, yet have the variable set. Looks like dual boxing error. VOIDWALKER_OP_126 should have been automatically flagged on completing BATTLE_ON_A_NEW_FRONT, which the database doesn't show you as completed either.

I've force completed BATTLE_ON_A_NEW_FRONT and force flagged VOIDWALKER_OP_126 which should allow progress from here since you already have the tier III white stratum abyssite (or the variable could not have been set like it is).

**Comment by qiganggang** [comment]
![qq 20150921215323](https://cloud.githubusercontent.com/assets/13742980/9993610/3b49c68a-60ab-11e5-824d-4b11174b4d81.jpg)
got It  thanks
