### ISSUE TITLE
Blessed Pumps +1 not selling at the AH

### ISSUE THREAD

**Issue by Alizoutim** [LegionDark/Issues#34]
**Date & Time**: 05/29/2015
**Frequency**: Always
**FFXI Client Version**: ver.30150508_5
**Character Name**: Alizoutim
**Race**: TaruTaru
**Main Job**: WHM -- same bug with any job
**Sub Job**: RDM -- Same bug with any sub job
**Area & Coordinates**: Mog House-Lower Jeuno-San Doria
**Party or Solo**: Both
**NPC Name**: @AH sell tab
**Steps To Reproduce The Issue**:
1-Buying Blessed Pump +1 from the ah with the cmd @ah
2-Equiping the item for some time 2+ week
3- Selling Blessed Pump +1 to the ah with the @ah cmd
4-Waiting 2 days (earth time)----> Item not sold
5-Going to Jeuno ah and canceling the sell
6- Selling the Blessed Pump +1 Again via @ah cmd
7- Waiting 24hour (earth time) ----> Item still not sold
8- Leaving the item in the Ah so GM could see

**Comment by R3P0FFXI** [comment]
How much are you listing the item for?

**Comment by Alizoutim** [comment]
3 000 000 gil same price i bought it and same price that is listed in the check price tab

**Comment by Alizoutim** [comment]
i also just realized that the last time it was bought/sold in the check price that is not correct as it state that it was in dec 2019 so this might be the problem if the AG went out of sync for this item

**Comment by R3P0FFXI** [comment]
Price was changed a while ago to 130k the issue is that you have it up for to much, reduce your price and the autobot will purchase

**Comment by Alizoutim** [comment]
firs of all did you check the price history of the item because EVERYONE bought it at 3 000 000 because it is the price that is writtend there.

secon when you put an item at the ah and the price is to high the auto bot send it right away in your MH to resell it.

IF and i really say IF the actual price is indeed 130k then MABY it should be a good idea to change the history because that is stealing from player

**Comment by R3P0FFXI** [comment]
We warned players of the pricing changes ages ago, when we find issues with pricing it is changed usually en mass. We are unable to change the history in the AH. We are stealing nothing from anyone as gil is worthless on this server and easy to come by.

**Comment by TeoTwawki** [comment]
1) The bot doesn't auto send it back to you. The auction server itself will return unsold items after the expire time (default 3 earth hours).

2) Gil on Legion server is absurdly easy to gain, please do not get so upset about it and sling strong language like stealing when simply saying ppl who spent the 3 mil should get it back most likely would have resulted in just that (that would be up to @R3P0FFXI to decide). Also see final remark about costs at the AH.

3) in retail when a price drastically drops after an update, you don't see SE compensating them. Legion has a bot simulating an always present seller constantly supplying items and simulating an always present buyer for every item, and just like on retail when a price gets changed through new listings being a different value the old history is still present. That doesn't mean we'll never edit the history when suggested, but we really can't take the time to poor over the AH listings with a fine toothed comb for these issues either even when trying to fix goofy pricing either. 

4) There are several quirks to the system that can't really be helped atm, like some time stamps being set years into the future to prevent the bots items form being returned to a character that does not exist and the fact that for now you usually get back the same amount you spent so AH gear is essentially "rented" ***for free*** except in these rare cases of a change....

There's a lot of work involved in trying to stop AH loopholes and not screw over every player. Sometimes things slip through the cracks or we have to change a price afterward and players will feel they were ripped off for having paid the old price. 9 times out of ten, I am not inclined to compensate past purchasers because sh-- happens and the system as it is is ***far*** more generous than retail would be. Try to imagine how a retail GM would react to being told you were stolen from because the item you paid 3 mil for now only sells for 130k.

**Comment by Loki79** [comment]
The fact that this actually made it to a bug report makes me laugh.
