### ISSUE TITLE
Ragnarok Relic Trials: Dune Widow

### ISSUE THREAD

**Issue by ivanmn** [LegionDark/Issues#352]
Date & Time: September 28 2015
Frequency: Once
FFXI Client Version: 30150730_2
Character Name: Orichi
Race: Taru
Main Job: Warrior
Sub Job: Samurai
Area & Coordinates: Eastern Alteppa Dessert, (G-8) 
Party or Solo: Party
NPC Name: Dune Widow
Monster Name: Not applicable
Multi-boxing? (multiple clients on same connection): NO
Steps To Reproduce The Issue:

Camped Dune Widow for a good 2-3 hours. Finally popped. Killed it with Ragnarok equip (notice the resolution with low damage highlighted in picture below). Auto attacked it to death. Didnt register as a trial kill. 

![orichi_2015 09 28_201546](https://cloud.githubusercontent.com/assets/14860280/10146012/73969cc0-661e-11e5-9b7c-ecf76f7d03f6.png)

**Comment by TeoTwawki** [comment]
Shoudl eb fien now, a nil placeholder for the NM was causing the script to exit prematurely, possibly from some GM force popping it repeatedly without taking care of the placeholder mob(s) ..

I've re-arranged the code to try and exec the trial stuff before the rest to hopefully prevent that from ever happening again, and verified it does work right now:
![screencap, trimmed](http://s10.postimg.org/a1vdi7epl/image.png)

As for resolution, that would be a separate issue if it wasn't normal. But for teh conditiosn its under, that looks pretty normal to me. Consider: this server doesn't use the post Adoulin ws math at all. That ws is not being used with the gear you would use on retail. The mob its being use don, has been buffed compared to retail. The weapon itself the ws was performed with, does not have the damage of a weapon you would be using it with at your level, on retail. Compare with your other greatsword ws under the same conditions, tp level, character level, mob, skill, gear, attack, str, and you'll see none of them do any better. 

The ws math except in a handful of customized cases, is all what retail had pre-Adoulin and has been verified correct, if you feel that is not the case you'll have to convince [DarkStar](https://github.com/DarkstarProject/darkstar/issues) of that because the Legion server has no intention of changing it to a custom ws script at this time.
