### ISSUE TITLE
Lost Attestation of Vigor

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#360]
Date & Time: 29/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_2
![aurel_2015 09 29_182235](https://cloud.githubusercontent.com/assets/13084662/10178938/d8c9a4c2-66d0-11e5-9733-cc14a51afbcd.png)

Character Name: Aurel
Race: Hume
Main Job: Sam and Drk
Sub Job: Sam/Drk
Area & Coordinates: none
Party or Solo: Party or solo 
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): no 
Steps To Reproduce The Issue: I do not understand why you lose

**Comment by nekrol** [comment]
![aurel_2015 09 29_182323](https://cloud.githubusercontent.com/assets/13084662/10179616/1bd2f0e4-66d5-11e5-80c2-303ae5a7d0cc.png)
I check my inventory item i have not

**Comment by R3P0FFXI** [comment]
when you learn not to dual box dynamis you can open tickets again

**Comment by nekrol** [comment]
login a friend Qigang my char which is not the problem that,not to dual box

**Comment by nekrol** [comment]
Issues #280,had already reported, I do not speak English use google, it's not always clear to me

**Comment by TeoTwawki** [comment]
Nekrol, what is your native language? I can try to help if it is Italian, German, or Chinese.

**Comment by nekrol** [comment]
Spanish

**Comment by TeoTwawki** [comment]
Hmm. My spanish stinks..but gonna try anyway.

Usted hacer, de hecho, ya tienen este. Estoy buscando a la derecha en ello ahora mismo en su carácter. Usted tiene el error de visualización conocida no mostrando, pero que está ahí.

Y R3 está molesto con la gente que usa múltiples personajes forman misma conexión a Internet (no importa cuyo carácter) para ciertas áreas, ya que se colgará el servidor a veces.

Hay un mensaje de advertencia para los efectos que de la zona, pero por desgracia no se puede mostrar el mensaje en varios idiomas. Habló con algunos jugadores bilingües para tratar de difundir la palabra.

I hope that came out right. English version below.

You do in fact already have this item. I am looking right at it right now on your character. You have the well known display bug not showing you it, but it IS there.

And r3 is upset with people using multiple characters form same internet connection (does not matter whose character) for certain areas because it will crash the server sometimes.

There is a warning message for the area's it effects but unfortunately I cannot display that message in multiple languages. He reached out to some the bilingual players to try and spread the word.

**Comment by TeoTwawki** [comment]
If I got any of that wrong, I hope it was at least humorous.

**Comment by nekrol** [comment]
Dual box that is clear to me by a friend that helped me advance the dyn using my other char

**Comment by TeoTwawki** [comment]
He thought you logged in that friends character. Thank you for explaining.

**Comment by PikaFox** [comment]
![tarot_2015 09 29_233710](https://cloud.githubusercontent.com/assets/12601727/10183914/29594fc8-6703-11e5-9355-586bf0c73307.png)

**Comment by PikaFox** [comment]
Check your mog house/case/storage/etc, you already have the item on your char.

**Comment by TeoTwawki** [comment]
Use sort command on each container.

**Comment by nekrol** [comment]
I can not find it in my inventory

**Comment by TeoTwawki** [comment]
Its is definitely there. Was Aurel a transferred character?

**Comment by TeoTwawki** [comment]
looks to be occupying the 1st slot of container 6, mog case.

**Comment by nekrol** [comment]
yes

**Comment by TeoTwawki** [comment]
nvm, not sure which thing is the container with ID 6...

**Comment by R3P0FFXI** [comment]
Nekrol mis disculpas por el tono duro de mi respuesta . Vi a ambos personajes ingresados ​​y asumí que estaba controlando ambos.

Basado en la suya y Teo comenta voy a seguir adelante y volver a abrir el tema y asignar a él.

Nekrol my appologies for the harsh tone of my response. I saw both characters logged in and assumed you were controlling both. 

Based on yours and Teo comments I will go ahead and reopen your issue and assign it to him.

**Comment by nekrol** [comment]
thank you

**Comment by TeoTwawki** [comment]
I think I have the answer finally. I will need to do the fix while the server is offline during next maintenance.

**Comment by TeoTwawki** [comment]
Next time you log in check your mog case and mog sack. May have to sort but should show up now

**Comment by nekrol** [comment]
thank you                                           
![captura](https://cloud.githubusercontent.com/assets/13084662/11168325/dbdf5f9a-8b69-11e5-96ba-cbcd1e1a7b9a.PNG)

**Comment by TeoTwawki** [comment]
Thank you for confirming.
