### ISSUE TITLE
ZNM ???s can eat pop items if mob isn't spawnable

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#380]
**Date & Time**: 10/15/15
**Frequency**: Often
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Nin 
**Sub Job**: War
**Area & Coordinates**: multiple  (Halvung in this case for example)
**Party or Solo**: Alliance 
**NPC or Monster Name**: Multiple (17031609 for the ??? in this example; Dextrose spawn)
**ffxiah.com link (for inventory items only)**:  NA
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Sometimes if the mob hasnt fully despawned the ??? spawn point will eat your item and be unable to spawn the mob. Happened with Dextrose, and has happened with multiple other ZNMs in the past.

**Comment by TeoTwawki** [comment]
:cry:  /wrists

**Comment by TeoTwawki** [comment]
effing dee-esss-pee didn't check the mobs action state in the conditions.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2272/files?w=1

2 birds one stone. This will nor be fixed in legion till after that update gets pulled in after DSP merges it though, so leaving issue open as a warning/reminder till then, unless R3 or Loki would rather it be closed then they can kill it.
