### ISSUE TITLE
missing key item white feather.

### ISSUE THREAD

**Issue by vashzx1** [LegionDark/Issues#388]
Date & Time: 10-18 11:02
Frequency:often
FFXI Client Version:30150910_3
Character Name:Hisoka
Race:Mithra
Nation:Bastok
Main Job:Blu
Sub Job:dnc
Area & Coordinates: Rolanberry fields
Party or Solo:solo
NPC or Monster Name: Cavernous Maw
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection):No
Steps To Reproduce The Issue: im on mission 1-2 of the wings of the goddess expansion and i have my white feather but yet i went in the maw before and i @homepointed out and i think thats why i cant go back in but i dunno can someone check for me i just get "nothing happens" when i try to go back through the maw

**Comment by vashzx1** [comment]
still bugged i think when i went into the maw i @homepointed out and maybe thats why i cant get back in

**Comment by TeoTwawki** [comment]
which zone did you land in when you 1st arrived in the past? only that 1st location's present time counterpart will be unlocked for you, to unlock *other*maws in the *present* you have to use their past time counterpart..I'm going to go change the initial unlock to get all 3 area's around Jeuno at once because this comes up so often. Its not the one you original entered that sets it - its where you *landed* (until my change takes effect for new people going in for 1st time - I can't auto give existing players the other two, they have to unlock them normally).

**Comment by TeoTwawki** [comment]
maw confusion case number 4563452345 resolved.
