### ISSUE TITLE
City Voidwatch Some mobs not giving credit/bugged

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#393]
**Date & Time**:  10/21/2015
**Frequency**: constantly
**FFXI Client Version**: 30150730_2
**Character Name**: Maiku
**Race**:  Taru
**Nation**: Bastok
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**: Pashow Marshlands [S]
**Party or Solo**: party
**NPC or Monster Name**: Veridical Conflux
**ffxiah.com link (for inventory items only)**:  n/a
**Multi-boxing? (multiple clients on same connection)**: yes at first, no 2nd round
**Steps To Reproduce The Issue**:
maiku, pebkac, vonku, digweed, avalon, devon, boroka, pauly, mrslave, gleks, alesaye, alessa, aisha are all having this issue.  Basically we did not get credit for (2?) NMs for city voidwatch i think?.  All of our characters have 'crimson stratum abyssite IV'  'indigo stratum abyssite IV'  'jade stratum abyssite IV'  hence we have killed every mob in tier 1-4 to upgrade our abyssites, but still missing credit for 1+ kills.  After we beat the final boss on tier 4 we went to the veridical conflux in pashow marshlands[s] and got the following: 'condition not met. variable 'vw 3 nation' value is 5 ..and must be 7' 'quest 'guardian_of the_void' status is : 0 and must be 0'  we do not have screenshots because all our abyssites upgraded to 4... meaning we killed all tiers... if not fix possibly tell us which we are missing so we cant try again.  I ran maiku/vonku/pebkac on 3 separate internet connections after the fact on 3 different PC's, neighbors house, my house, and a 2nd DSL drop i recently purchased through 2 different routers directly to the 2nd and 3rd PC.  I then ran through all the VW NMs a 2nd time and got the same issue.  It is not a dual boxing issue as far as i can see(unless it was the first time and now our chars are bugged).  Any help would be appreciated.

**Comment by TeoTwawki** [comment]
I the way DSP does its damnable socket connection 2 routers will still leave you with it occasionally screwing up, just so you know. Short of getting getting your isp to give you 2 separate physical connections there is no work around for it. This doesn't sound like a dual boxing bug though, I'll check into which one is missing in your variables tomorrow.

**Comment by TeoTwawki** [comment]
You need Celaeno killed again or the var set by a GM. I have changed the codnitions to prevent thsi from happening again, there were 2 bugs involved: that NM was checking the wrong KI, and if you spoke to a voidwatch officer a keyitem would be changed out due to a last minute programming oversight, so then you wouldn't get credit for his kill even if you avoided the Bastok VW officer.

Resets for 3 nations now happen on kill, not at the VW officer, and won't interfere with quest progress.

**Comment by TeoTwawki** [comment]
@Loki79 my change here also killed something we either didn't think of or didn't care about at the time. If someone had stored up the stones they could repeat the t4 NM till they ran out, because their Abyssite wouldn't go back to t1 till they want to the voidwatch officer for more stones. This was nerfed in the course of fixing the 2 bugs mentioned. If that was a feature not a bug, that'd take some small bit of extra work on my part later to put back.

**Comment by TeoTwawki** [comment]
@maikuru23 did you get either var set by GM or a new Celaeno kill yet?

**Comment by maikuru23** [comment]
yeah it was corrected the day you reset all the tier4's that were stuck.  Thanks
