### ISSUE TITLE
Nirvana (75) stats do not work

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#4]
**Date & Time**: 5/25/15
**Frequency**: NA
**FFXi Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Smn 79
**Sub Job**: NA
**Area & Coordinates (Type @where to get this info.)**: NA
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**:
Equip Nirvana (75)
Does not give any Avatar Perpetuation Cost Reduction
Assuming this is/will be true for all Nirvana upgrades
Assuming other stats on the item are also uncoded

**Comment by R3P0FFXI** [comment]
Tarot, 

Im guessing your bug is for Aftermath issues not stats, NIrvana has the following DSP MODS on it

MOD_ACC= 0x19 = +30
MOD_PERPETUATION_REDUCTION  = 0x15A = +4
MOD_ADDS_WEAPONSKILL = 0x163 = 187
MOD_DOUBLE_ATTACK = 0x120 - Occ Atk 2x

As of right now there is no way to script Occ Atk 2x for Avata that Loki or I know of, we will talk to Teo after maint to see if there may be a way to do this.

**Comment by R3P0FFXI** [comment]
Issue is not with Nirvana as it gives correct cost Issue actually appears to be with Chatoyant Staff and or Affinity calculations in DSP. New ticket to be opened for This
