### ISSUE TITLE
diabolos elevator

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#41]
**Date & Time**: 31/05/2015         16:21 GMT
**Frequency**: Stuck
**FFXI Client Version**  30150508_8:
**Character Name**: Gofer
**Race**: Taru
**Main Job**: BLU
**Sub Job**:NIN
**Area & Coordinates** Psoxja Diabolos elevator from Homepoint crystal:
**Party or Solo**: solo
**NPC Name**:
**Monster Name**:
**Steps To Reproduce The Issue** head to elevator got dragged noto the elevator while fighting diremites and couldn't get off. system message requested reporting of diabolos elevator bug

**Comment by TeoTwawki** [comment]
@goferffxi can you get me the (at)where position data for a spot as near to there as possible? Would appreciate it, helps me make sure I am looking at the right one (I always forget which of Pso'Xja's many elevators is which when pos jumping)

**Comment by goferffxi** [comment]
X-20 Y32 Z35 (197)  Hope this helps Teo

**Comment by TeoTwawki** [comment]
Thank you.

**Comment by TeoTwawki** [comment]
Likes like since DSP made the actual platform move now, our workaround to simply skip people up/down from before has positioning issues. I have commented out the actual teleportation for Tuesdays maint, and should elevators break in the future we can re-enable that. This means when Tuesday maint finishes,  these should work like retail again.

**Comment by TeoTwawki** [comment]
The cause was actually running onto the now mobile platform, which when we made our work around we were simply skipping it altogether.
