### ISSUE TITLE
Paramount Botulus doesnt spawn

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#461]
**Date & Time**: 12/6/15
**Frequency**: Twice
**FFXI Client Version**: 30151103_3
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Sam
**Sub Job**: Thf
**Area & Coordinates**: Legionhall Mul
**Party or Solo**: NA
**NPC or Monster Name**: Paramount Botulus/Gallu
**ffxiah.com link (for inventory items only)**:  NA
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Paramount Botulus doesnt spawn when doing the legion floor, making spawning Gallu impossible

**Comment by TeoTwawki** [comment]
The phuck? This hasn't been touched since forever ago, how can he be broken now all of a sudden..

**Comment by PikaFox** [comment]
No idea, but we checked in game and botulus didnt spawn for some reason.

**Comment by TeoTwawki** [comment]
Well..a lots going to be recoded for that massive update we're workin on, so he'll get fixed there I suppose.

**Comment by R3P0FFXI** [comment]
@TeoTwawki can we create a label for the Massive update so these can be put into that category?

**Comment by Samikana** [comment]
@R3P0FFXI @TeoTwawki I was the GM that tested this after players asked me to check it out, as well as @PikaFox asked me to check it on Skype.  

I re-spawned the floor by trading the trophy to the book.  The floor spawned as usual, and everything is working except for Botulus.  I killed everything and the result was consistent with their claims.  I spawned the floor for them so that they didn't waste their gil, because they had no way to know that the megaboss was malfuntioning.

I spawned Gallu because I didn't remember that Botulus spawns first (Sorry!) so I didn't get to check if Botulus works correctly and spawns Gallu.  I'll check when I get home and add the results here.

**Comment by Samikana** [comment]
@TeoTwawki officially not sure what's going on.  Botulus didn't spawn yesterday, twice.  Now it did.  Spawned Gallu no problem.
![halsey_2015 12 07_185210](https://cloud.githubusercontent.com/assets/12781975/11643694/b54f21e2-9d13-11e5-8b07-11cbf45cebba.png)

**Comment by Samikana** [comment]
There doesn't seem to be an issue anymore.  Botulus and Gallu spawned x2.

**Comment by TeoTwawki** [comment]
that makes no sense. it can't break then magically fix itself.

**Comment by TeoTwawki** [comment]
-*sprinkles holy water*- 
The power of open source compels you!

**Comment by Samikana** [comment]
The server has crashed since I last tested it.  Perhaps when it crashed, it began functioning normally again?

**Comment by TeoTwawki** [comment]
see if you can do 2 runs back to back, with  short delay after its death before next run

**Comment by Samikana** [comment]
@TeoTwawki I'm not home currently.  I will do it tonight.

**Comment by Samikana** [comment]
Going to close this.  I have popped legion 3 times and haven't had an issue and there has been no issue in the last week reported or even spoke of.  Create a new bug report or ask a moderator to re-open it if it starts happening again.
