### ISSUE TITLE
Tiny bug on the new blue mage spell list on the website

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#49]
Plenilune Embrace is listed twice, other than that all good as far as I can tell.

**Comment by atom0s** [comment]
It is listed in the database twice. So this seems to be something that will need to be looked into by @TeoTwawki

**Comment by Genesis-Legion** [comment]
I looked at both listings of it, and both seem to be identical so it might just be a duplicated entry.

**Comment by atom0s** [comment]
In the database they have different entry info:
http://i.imgur.com/za2Upnp.png

**Comment by Genesis-Legion** [comment]
that's pretty weird, anyhow I just thought I'd bring it up.

**Comment by TeoTwawki** [comment]
Some blue spells have more than one ID for the skill, and if we don't list them twice we wind up with the spell sometimes not being learn-able. In this case I think its the alternate for when gnoles are standing upright as instead to on all for legs, so that the spell can be gained from being used in either stance.
