### ISSUE TITLE
Relic credit

### ISSUE THREAD

**Issue by trueamer** [LegionDark/Issues#499]
**Date & Time**: 05 Jan 2016
**Frequency**:Once
**FFXI Client Version**:30151204_2
**Character Name**:Trueamer
**Race**:Human
**Nation**:Bastok
**Main Job**:Ninja
**Sub Job**:Dancer
**Area & Coordinates**:X:-39 Y:0 Z:45
**Party or Solo**:Solo
**NPC or Monster Name**:Adamantoise
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**: I saw another post that addressed the same issue. I have the screen shots here

![weapon in hand](https://cloud.githubusercontent.com/assets/16568100/12132597/f3809bcc-b3e2-11e5-99f2-e55b4136a232.PNG)
![no trial rewarded](https://cloud.githubusercontent.com/assets/16568100/12132600/fc20d418-b3e2-11e5-91a1-1d6a8ad6a39b.PNG).

**Comment by trueamer** [comment]
Fafnir same thing
![fafnir](https://cloud.githubusercontent.com/assets/16568100/12133091/942619f4-b3e7-11e5-9e28-f3a489e21d55.PNG)

**Comment by TeoTwawki** [comment]
2 tips for you:

Please don't put screenshots in the middle of the template, in the future put them after (I have edited your post to fix this).

Please make sure your ffxiah link is correct for the item (which you didn't include) and if sending screenshots highlight the weapon you are doing the trial on for these. Either/Both of these things helps us help you faster, because then we can see which of the multiple identical named items you are equipped with at the time without having to check after the report was made (I know what the code says, but I need to compare what you have to know if my code is using an incorrect item ID someone plugged into it).

I know these haven't been changed in a long while and were working with other relic items (multiple Excaliburs have been made) so I am hoping a few items got their IDs mangled (wrong tiers ID in wrong column) which will be a fast easy fix if so.

**Comment by Samikana** [comment]
@trueamer please send Halsey a tell in-game and I will update your trial for the mean time

**Comment by Samikana** [comment]
Teo fixed this.
