### ISSUE TITLE
Lost all my Homepoints

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#522]
I noticed this after God disabled the @homepoint and @return commands. But I haven't been in the game since then and wanted to see if it got reproduced or a one time thing and I'm still having no homepoints. Is there a way to restore this?

Character is Erinyes. All other chars of mine are fine, just that one got deleted for some reason.
![img_20160119_215039](https://cloud.githubusercontent.com/assets/15023912/12440997/3e7d5146-bef7-11e5-8b41-f03610ee70e7.png)

**Date & Time**: all the time
**Frequency**: all the time
**FFXI Client Version**: 30151103_3
**Character Name**: Erinyes
**Race**: Mithra
**Nation**: Bastok
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**: Everywhere
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes, Oscar, Cureslave, but no problems.
**Steps To Reproduce The Issue**: Tried relogging several times, tried different homepoints, only logged one char at a time

**Comment by Samikana** [comment]
You went into an Adoulin area.  Your fault.  This is set up specifically to keep players from accessing the areas.  Going to have to recollect them.

**Comment by TeoTwawki** [comment]
In the event anything other than the auto-wipe mechanism causes any changes to home point, there is nothing that can be done about that ***anyway*** so either way there would be nothing to do here / can't help you. And none of the ways besides that are capable of wiping homepoints, you'd just get random garbage instead. Note that random garbage homepoints are likely to occur anytime darkstar changes the homepoint teleport system even just to add new ones. its happened before. Never has resulted in totally empty lists though.

About the auto wipe mechanism:
A long while back i deliberately set up all homepoints you aren't supposed to have to auto wipe the entire homepoints list and send the character elsewhere, because manipulating the data to remove just 1 homepoint is a colossal pain in the rear, and this auto punished people abusing the homepoint teleports. 

This stops exploiting and bugs related to those zones and objects in them that were occurring from people deliberately using darkstars glitches to teleport to those zones. It was this or disable the teleports completely.

**Comment by warlord1352** [comment]
yeah thats what tarot told me after i posted this. thanks for the info tho, I didnt know that was there like that.
