### ISSUE TITLE
Dnc Level 40 Relic NM fight

### ISSUE THREAD

**Issue by daronis17** [LegionDark/Issues#525]
I tried fighting the NM for the dancer level 40 relic offhand quest solo and got 3 shot.  I am level 50 with the best gear I can have and it hit for 270 per auto attack.  I came back a few hours later with a friend who was also level 50.  The mob had not despawned so we engaged.  Most of our attacks did not hit the mob and we quickly died.  Is it possible the mob is not the right level for the quest?  It seems really hard compared to other job's level 40 relic NM's.  (We did the dark knight quest together and that NM died in about 4 attacks from both of us and we took minimal damage).

**Date & Time**: 1/20/16 - 10:44PM
**Frequency**:twice
**FFXI Client Version**: 30151223_0
**Character Name**:Jordia
**Race**:Hume
**Nation**:San d'Oria
**Main Job**:Dancer
**Sub Job**:Warrior
**Area & Coordinates**:Grauberg[S] F-6
**Party or Solo**:Duo
**NPC or Monster Name**:Migratory Hippogyrph
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:no
**Steps To Reproduce The Issue**:

**Comment by Samikana** [comment]
All AF is sold at the armor storage guy.  One is Sinon in Bastok Markets

**Comment by PikaFox** [comment]
Honestly im surprised it even worked at all. Do not expect quests for AF ToAU+ to work properly. Im 90% sure this is a DSP specific thing if it is the incorrect stats for the mob and not legion specific.

Also, as Sami mentioned, the AF storage NPC has *all* AF armor stored and available because of the numerous DSP AF quest issues, so its unlikely legion will get to this soon, if at all.

**Comment by PikaFox** [comment]
Also.... my github randomly assigned my hotmail avatar now.... huh.

**Comment by TeoTwawki** [comment]
That sorta insanity is fairly normal for AF quests anyway. Ask anybody that actually tried to do their AF quests on retail at the lv you could first do it without any high level help. Can you say squishy helpless players?

But yeah I am surprised the mob *even spawns at all* because so much of that stuff doesn't even exist in DSP man...

**Comment by daronis17** [comment]
Thanks for the fast reply and the info about the vendor for artifact gear.  It does sound like SE to make a quest stupidly hard like that.  Sorry to bother you all.
