### ISSUE TITLE
Wingcutter +1 broken

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Issues#567]
**Date & Time**:  Feb 04 2016
**Frequency**: Always
**FFXI Client Version**: 30151204_2
**Character Name**: Vida
**Race**: Mithra
**Nation**: San d'Oria
**Main Job**: THF
**Sub Job**: NIN
**Area & Coordinates**: Port Jeuno
**Party or Solo**: Solo or Party
**NPC or Monster Name**: -
**ffxiah.com link (for inventory items only)**: Wingcutter +1 
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Cant equip the weapon (range).

![vida_2016 02 04_160854](https://cloud.githubusercontent.com/assets/16524259/12809448/2851a9f2-cb5a-11e5-8b2e-714c35c23362.png)

**Comment by Samikana** [comment]
Jobmask probably needs fixed.  will fix this with SCH Empy

**Comment by Samikana** [comment]
@TeoTwawki I think that the fix that I sent into Loki from #435 never made it into the game, this is the THIRD report we've gotten about this item.

**Comment by TeoTwawki** [comment]
> never made it into the game

Yeah because some issues were closed when code was written instead of when that code actually becomes active on the server. The server hasn't pulled in those changes since before November, only getting hackishly adjusted\* so the client would work. Everything else is in that huge update we've been waiting on.

###### \* _Even that has stopped because I put my foot down and dealing with 500+ broken files and edit conflicts per merge._

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
