### ISSUE TITLE
Mob depoping after a  death caused by charm

### ISSUE THREAD

**Issue by Genesius1490** [LegionDark/Issues#592]
Date & Time: 10/02/2016
Frequency: always
FFXI Client Version: 30151204_2
Character Name:Genesius
Race:Hume
Nation:Bastok
Main Job:NIN
Sub Job:WAR
Area & Coordinates:any zone
Party or Solo:both
NPC or Monster Name:Chariots, frogs, Caturae
ffxiah.com link (for inventory items only): ---
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: Mob use a charm move on my NIN and then my NIN oneshot any person around me cause I have no time to unequip my kannagi119/kikoku. when everyone is dead the mob just despawn instead of staying. making me unable to do any of those mobs most of the time

**Comment by TeoTwawki** [comment]
specific mob names needed in order to fix. its caused by improper spawn command in script. Its actually not related to charm: the command mistakenly used sets a timer that is only checked when mob is unclaimed, the the timer itself was started when the mob was spawned (people using said command mistakenly beloved this would start the timer after claim was lost). Its all the F over in darkstar itself.

**Comment by Samikana** [comment]
Teo a TON of mobs do this, I've never actually experienced a mob that charms that doesnt despawn.  I'd compile a list but have no playtime atm.

**Comment by TeoTwawki** [comment]
@Samikana reread what I wrote. I'm not wrong, the reason you see it with charm is its declaiming. not because charm itself depops the thing doing the charming.

**Comment by TeoTwawki** [comment]
@Samikana `SpawnMob(17072172,180):updateClaim(player);` <- in that example code, after 180 seconds pass any loss of claim will ***INSTANTLY*** depop the mob. dsp does this in nearly every single case, because script authors didn't know wtf they were doing. feel free to poor over every dsp script and adjust the ***THOUSANDS*** of them that are incorrect. its that 180. it doesn't belong there.

**Comment by Genesius1490** [comment]
Rani - Irriri Samariri - Long-Barreled Chariot the main ones I've seen doing this

**Comment by TeoTwawki** [comment]
@Genesius1490 ty, will fix them in update

**Comment by Baucant** [comment]
@TeoTwawki  addd Cirein-croin to the list

**Comment by TeoTwawki** [comment]
@Baucant thx

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by TeoTwawki** [comment]
I need a volunteer to compile a solid list of mobs that still do this after the update. Its a DSP issue, but I need it for awareness reasons.

**Comment by Baucant** [comment]
Add Jailer of Love to the list
