### ISSUE TITLE
Unable to dualbox anymore, might need account info reset.

### ISSUE THREAD

**Issue by Genesius1490** [LegionDark/Issues#597]
**Date & Time**: 12/02/2016 -- 00:19 a.m GMT
**Frequency**:Since today
**FFXI Client Version**:30151204_2
**Character Name**:Genesius and Jenna
**Race**:Hume and Mithra
**Nation**:Bastok
**Main Job**:NIN and WHM
**Sub Job**:DNC and RDM
**Area & Coordinates**:any
**Party or Solo**:both
**NPC or Monster Name**: ---
**ffxiah.com link (for inventory items only)**: ---- 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:
Log in Genesius as usual and then try to Log in my whm mule Jenna in but I get the log error message "failed to bind to listening socket". Then game starts, can choose Jenna as character and she gets stuck in downloading data. when game eventually crash I get back to the character option and now it shows "Genesius". I tried uninstalling ashita and reinstalling it, I tried restarting PC, also tried restarting Router and CMD ipconfig /flushdns. But this thing still happens.
Happens as well when I log Jenna first then try for Genesius.

Link to an image of it: http://i.imgur.com/8CqeH5E.png

**Comment by TeoTwawki** [comment]
Whatever got you stuck in unrelated to that error message. The error message I normal when running multiple clients, just means it couldn't make a socket because it already existed (and because DSP only makes one socket currently, so the loader can't use more than one like retail would).

**Comment by TeoTwawki** [comment]
Are any of your alts showing as online when you aren't?

**Comment by TeoTwawki** [comment]
p.s.
Its also normal for it to show the wrong character roster after that - you have to completely exit the client and then relog any time you hit a login error (and also never begin the login process on another account before the preceding one is fully in game). Its caused by the same thing as that error message.

**Comment by Genesius1490** [comment]
I have been waiting first account to be fully logged in before trying to log in second

**Comment by TeoTwawki** [comment]
yeah but once you error, don't go back into char select (you did, which is why you saw wrong characters). exit out entirely instead and then relogin that account. I'm uncertain if the first account will suffer any ill effects, its possible thats a trigger for the well known in game dual box glitches (missions not counting, etc).

**Comment by TeoTwawki** [comment]
I'll be around in irc tomorrow if it persists

**Comment by Genesius1490** [comment]
seems like it fixed itself for now. zoned main to another zone before trying to log second. dunno if it helped
