### ISSUE TITLE
Mah trials dun werk! ITS BROKE!

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Issues#644]
All relic and mythic custom trials are disabled until I have time to deal with the large portion of cheating turds on this server.

I have also been made aware griefing of players who report these cheats. This is not "narcing" **If someone reports an exploitable bug and anyone gives that person any grief over it, justice will be swift and harsh. Tyrant Teo has spoken.**

**Comment by atom0s** [comment]
The rise of exploits that has started happening in the last few months is becoming a major problem.

People are asked countless times to report these problems as soon as they are found and instead, you are all abusing them for your own good. Let it be known that there are methods of seeing who has abused these types of things and the punishments are not going to be as minor as they have been in the past. Before, we have been pretty nice about handling exploits and handling those that abused it.

However, that is no longer the case. Punishments for exploits going forward are going to be game changing for those that want to exploit them and not report them. This issue is no longer going to be something taken lightly. If you want to exploit, you are basically going to not want to play here when the punishment has been applied.

Teo and the others put hours on hours of work into this server to give you something to play FOR FREE. Not a single dime is made with this server and yet you abuse that kindness and basically say fuck you to Teo and the others that put in the effort to make this server what it is. 

I can tell you now that I'm going to personally make sure that your lack of care for those that give you something for free is not going to be taken lightly.

**Comment by kelvenar** [comment]
So at first i wanted to say sorry, i did the kikoku trial and was 1/4 nidhogg kills. 
And i was told trials are kinda broken so i finished the trial killing another NM.
I didnt thought about it to be honest, so im sry for abusing this bug.

**Comment by Samikana** [comment]
The honesty/apology is appreciated but doesn't change the severity of the issue nor the offense.  Whether or not an apology is given or is sincere , players who abuse these bugs will be dealt with accordingly.

**Comment by R3P0FFXI** [comment]
Relics and Mythics getting deleted im done with this shit

**Comment by R3P0FFXI** [comment]
Issue resolved in next update
