### ISSUE TITLE
Sandy VW NM

### ISSUE THREAD

**Issue by djmanofsteel** [LegionDark/Issues#720]
**Date & Time**: around 2:00pm est

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Mano

**Nation**: BAstok

**Job(level)/Sub Job(level)**: War99/Sam49

**NPC or Monster or item Name**: Hahava

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**: Spawned VW nm and it just stood there after engaging seemed ok.
till it killed me and was not aggressive toward another player in party. finally under 60% mob acted more normal. did all TP moves correct. After 30 min. mob did not despawn. it started the text in chat of "You take to long. I'm outta here" and then went invisible and just had its name in red claimed.
proceeded to kill mob. when dead dropped 2 items. 1 item dropped fine and was able to be equiped.
other item was lotted on did not already have one and fell to the ground.
item name: Floestone
not asking for it, wanted it to be known that this happened.

**Comment by Samikana** [comment]
@TeoTwawki overlooked VwNM issue

**Comment by TeoTwawki** [comment]
This was already fixed. There is nothing in the script anymore to print that message. If you pop this NM today, before maint, it can't happen right now. The depop code was removed from all VWNM until it can be reworked and verified behaving as intended instead of buggy code being left out for players to unknowingly beta test.
