### ISSUE TITLE
Account for Grouchmonk, 5 characters missing from list in character choise screen

### ISSUE THREAD

**Issue by Grouchmonk** [LegionDark/Issues#726]
**Date & Time**:  03/18/2016, 09:52PM

**FFXI Client Version (use `/ver`)**:  Ashita

**Character Name**: Qyla, Wukie, Jyn, Grouchmonk & Nightsong

**Nation**:  Various

**Job(level)/Sub Job(level)**:  Various

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**:  N/A

**ffxiah.com link (for items issues only)**:  N/A

**Multi-boxing? (multiple clients on same connection)**:  N/A

**Steps To Reproduce The Issue**:  N/A

**Comment by TeoTwawki** [comment]
Going to need account names to go with the character names.

**Comment by Grouchmonk** [comment]
they were all on Grouchmonk account

**Comment by TeoTwawki** [comment]
I think I know why i see all chars in db just fine but you thought they were deleted. There are bugs with communication between client and server when multiple characters are on a single account. In efforts to avoid said bugs I warned the playerbase months ago that they should use multiple accounts and that I would move characters between accounts for anyone who opened a ticket. I think I need to do that for you. You were unaffected until recently because the limit wasn't being enforced+you were lucky.

If you make a 2nd account I can move the ones of your choosing. 3 per account. More than that we randomly see characters that can never log in.

**Comment by TeoTwawki** [comment]
Apologies for the inconvenience.

**Comment by Grouchmonk** [comment]
cool, I will make 2 new accounts tomorrow & e-mail the details, is that 
ok, or do you want me to wait longer?

**Comment by TeoTwawki** [comment]
you can PM me in IRC or on the forums, or post here (I don't need the passwords or anything, just the account+character combinations)

**Comment by Grouchmonk** [comment]
I created 2 new accounts: Marketgarden, the Characters Grouchmonk & 
Wukie can be placed there. 3rd account: Overlord, Jyn & Nightsong can be 
placed there, The Character Qyla I had trouble with & was unable to log 
in w/her, I do not know if it is a broken character or not, if she is 
"repairable' she may be placed on the account Overlord aswell.

**Comment by TeoTwawki** [comment]
Ok Grouchmonk and and Wukie have been moved to Marketgarden, Jyn and Nightsong have been moved to Overlord. Check and see if any are still missing or otherwise unable to log in.

**Comment by Grouchmonk** [comment]
all 4 are back, & I am able to log on w/them, thanx so much, I know you 
folks are busy w/the update issues, thanx for taking the time to help me 
out :)

**Comment by TeoTwawki** [comment]
Qyla works to now? I was thinking that, was probably from the very bug I was talking about before so the move would fix it..

**Comment by TeoTwawki** [comment]
If all working, we can close this.

**Comment by TeoTwawki** [comment]
Open a new ticket if Qyla can't login.
