### ISSUE TITLE
Issue w/ 7 Wonders Mobs

### ISSUE THREAD

**Issue by Xenres** [LegionDark/Issues#729]
**Date & Time**: 3/19/2016 1311 JST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Zenephret

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: MNK99/WAR49

**NPC or Monster or item Name**: NPC (lol the wonders mobs)

**Zone name & Coordinates (use `@where`)**: Tahrongi/Valkrum/Temple tested so far

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce The Issue**: The 7 wonders mobs will let you beat them (probably to death) without ever taking any actions. Letting him punch down the bird to see if anything actually happens. Going to test out the others on an alt.

**Comment by TeoTwawki** [comment]
@R3P0FFXI if you want to can try and comment out their spawn/respawn in scripts and use `@despawn` to put down any that are up. Its going to be awhile before their mobskills are restored.

**Comment by w3genesis** [comment]
Went and beat Tchakka and Hurkan to death, mob didn't attack or ws, but did use different 2h multiple times(mighty strike, blood weapon, hundred fist, chainspell etc). Tossed all drops from them so as not to be unfair.
Noticed that many other NM also have their ws missing, but at least their melee attacks still hurt. Instead of despawning them till skills are fixed, would be fun to give them auto-attack with much higher attack speed and damage coupled with the 2h spam, so it will be a completely different challenge for now.

**Comment by R3P0FFXI** [comment]
@TeoTwawki 7 Wonders should now be disabled per our discussion, I have built the mob skill lists and uploaded to the tracker.

@w3genesis mobs have been disabled for now

**Comment by TeoTwawki** [comment]
has been fixed, mobs re-enabled
