### ISSUE TITLE
Sandoria Mission 2-3, Post dragon fight cutscene not occuring.

### ISSUE THREAD

**Issue by Bovice1** [LegionDark/Issues#758]
**Date & Time**: 3/21/2016 11:30 PM

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Bovice

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 75MNK/37WAR

**NPC or Monster or item Name**: Black Dragon

**Zone name & Coordinates (use `@where`)**: Windurst Woods

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Fought the dragon for Sandoria rank mission 2-3, got the cutscene after the fight and lost the key item to enter. The next step requires talking to NPC Mourices in WIndurst Woods for a cut scene, but when I speak with him he just gives text regarding fighting the dragon which is only suppose to occur before the fight and receiving the black key which also when speaking to the NPC Kupipi she does not give another black key, so I cannot continue the mission or repeat the fight.

![blackdragonfightclear](https://cloud.githubusercontent.com/assets/17997739/13941378/771f2cc6-efbd-11e5-91b2-1531562f4486.png)

**Comment by Samikana** [comment]
Did you have this issue prior to the update?  If so, your variable is already off and needs to get manually set.

**Comment by TeoTwawki** [comment]
@Samikana @PikaFox just so you guys know, update should have fixed client version related stuff like the CS freezing because it couldn't find the NPC with the right ID in the client, but many of Darkstars NPCs will still suffer from HD (_Halver's Disease_) and screw people's variables through otherwise innocent interactions. Like accidentally talk to wrong consulate and get mission progression busted when that NCP should have done nothing at all since its the wrong nation. Stuff like that.

If only we had quality lua script scientists who could make a cure! We already know who patient zero is, if only he had been quarantined before it was too late.

**Comment by Bovice1** [comment]
This happened just last night around 9PM EST, so after the update I believe.

**Comment by Bovice1** [comment]
Also I'm fairly new to the server. Should I contact a GM in game or just wait for a response? Sorry, don't mean to sound needy.

**Comment by TeoTwawki** [comment]
@Bovice1 one should contact you either here or in game. If here probably to find a spot where your in game schedules match.

**Comment by Bovice1** [comment]
@TeoTwawki Ok thank you.

**Comment by Samikana** [comment]
I will not be able to log into the actual game until Thursday night or Friday.  @PikaFox will have to fix you, and if he doesn't get on in time to, you'll have to wait for me.

**Comment by Bovice1** [comment]
@Samikana No problem, I appreciate the help.

**Comment by PikaFox** [comment]
Set var, gave KI. Player didnt receive KI from fight nor did the var get set.

Player was able to progress.
