### ISSUE TITLE
Halvung Operating Lever Gates Not responding.

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#77]
Date & Time: 6/07/2015
Frequency: Happened  to several people 
FFXI Client Version: 30150508_8
Character Name: Daedrik
Race: Elvaan
Main Job: PLD
Sub Job: RDM
Area & Coordinates:  G-8 Halvung Map#2  and J-9 Halvung also Map#2
Party or Solo: Party
NPC Name: Operating Lever
Monster Name :
Steps To Reproduce The Issue: Hit lever and watch nothing happen

**Comment by TeoTwawki** [comment]
Should be all better after next maint.

I added non retail hack some lever NPCs to try and make every door in Halvung able to be opened with a single script without a bunch of getPos() or static ID checks.

Do to it proper I'd either need to rename NPC's to have separate scripts for each level, or check the positions, or static check the NPC IDs. Since we don't give a crap, I just had each level trigger a bunch of openDoor() for IDs around it. As a side effect a lever may run the openDoor() command on the wrong NPCs in addition to the correct ones, which should be harmless.

**Comment by TeoTwawki** [comment]
Closing this, if we have any problems that are after maint can post back here and if needed I can re-open this.
