### ISSUE TITLE
PM2-3  Distant Beliefs final CS bugged

### ISSUE THREAD

**Issue by Alizoutim** [LegionDark/Issues#78]
**Date & Time**:  6/8/2015 2:19
**Frequency**: Always
**FFXI Client Version**: Lastest
**Character Name**: Alizoutim
**Race**: Taru
**Main Job**: Blu
**Sub Job**: Dnc
**Area & Coordinates**: Tavnazian Safehold
**Party or Solo**: Both
**NPC Name**:Justinius
**Monster Name**:X
**Steps To Reproduce The Issue**:
1-Finish the Distant beliefs battle in phominia aqueduc
2- go in town for the cs
3- Talk to Justinius
4- Cs start and stop playing when the little green hair taru is about to talk

**Comment by TeoTwawki** [comment]
> FFXI Client Version: Lastest

Always use the output of the ```/ver``` command or when one can't get into game, the version reported in playonline's file check menu.

I've seen people have this problem before, and when I check it that cs plays through without error for me, its been a problem on the client side end every time thus far.

### Things to try: 
* using no plugins
* using no windowing apps at all (xiloader directly, rather than ashita or windower)
* forcing an update check (this is ***not*** the same thing as a file check)

**Comment by Alizoutim** [comment]
Thank you closing all plugin seem to have fix the problem

**Comment by TeoTwawki** [comment]
Betcha it was taht oen that auto advances dialogs. Seems to mess up quit a few cs..I think eternity is its name? Not sure.

**Comment by Alizoutim** [comment]
no all i have is  -config - minimap - timer

**Comment by TeoTwawki** [comment]
Ah. Well if you happen to know/find out which plugin specifically was doing it, let me know and I'll add it to my shortlist of suspects for next time cs's are failing for someone. :grin:

**Comment by atom0s** [comment]
Had this bug happen tonight while working on CoP on an alt character. Still seems to be an existing issue.
