### ISSUE TITLE
NPC doesnt attack

### ISSUE THREAD

**Issue by Minikay** [LegionDark/Issues#782]
**Date & Time**: 3/25/16

**FFXI Client Version (use `/ver`)**: recent one

**Character Name**: minikay

**Nation**: sandy

**Job(level)/Sub Job(level)**: thf99

**NPC or Monster or item Name**: NPC ( i dunno the name)

**Zone name & Coordinates (use `@where`)**: vaklurm dunes

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: NPC is a shark. HE doesnt attack and is named NPC.

**Comment by TeoTwawki** [comment]
The being displayed as NPC is normal for him. The not attacking isn't
:disappointed: 
Shark, Y U no eat player anymore?

**Comment by Hallabaloo4** [comment]
It seems as though none of the 7 wonders are currently attacking back at the moment. They use their 2hr skills every once in a while but at no point do they do anything that deals damage to the player. All normal items seem to drop upon death as usual as well.

**Comment by TeoTwawki** [comment]
Probably they all had melee specials replacing the standard melee attacks. That'll get fixed when I migrate their mobskilsl to the new scripts.

**Comment by Hallabaloo4** [comment]
Until is there anything to worry about in terms of killing them? I've seen a few groups killing them so far and really would rather not have everyone face God's wrath again for a small # of people exploiting

**Comment by TeoTwawki** [comment]
Theres to much busted to hold it against you guys, if anyone says otherwise direct them to me. In regards to voidwatch ones though, its waste of stones to try and I think GM God already told people not to, so that one I am staying out of and its on him (wrath be possible) since even the lsmes says to stay away form VW for now.

@R3P0FFXI Paging GM God...
Just want to make sure we're on same page. I am:
1. taking a quick stab at teh custom trials issue, if I can't immediately fix the trial issue, will move on
2. fixing mobskills for 7 wonders
3. rejoining you on the the VW mobskills
In that order.

**Comment by TeoTwawki** [comment]
Theres to much busted to hold it against you guys, if anyone says otherwise direct them to me. In regards to voidwatch ones though, its waste of stones to try and I think GM God already told people not to, so that one I am staying out of and its on him (wrath be possible) since even the lsmes says to stay away form VW for now.

@R3P0FFXI Paging GM God...
Just want to make sure we're on same page. I am:
1. taking a quick stab at teh custom trials issue, if I can't immediately fix the trial issue, will move on
2. fixing mobskills for 7 wonders
3. rejoining you on the the VW mobskills
In that order.

**Comment by TeoTwawki** [comment]
The "NPC" monsters should be attacking now.
