### ISSUE TITLE
Lost all registered Home Points

### ISSUE THREAD

**Issue by Hallabaloo4** [LegionDark/Issues#802]
**Date & Time**: 7:34PM PST 3/27/2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Halabaloo

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99SAM/49WAR

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Went to favorites on Bastok Mines Home Point, saw an adoulin one, clicked it out of sheer curiosity. Got teleported to adoulin then immediately back to Bastok Mines and all of my registered home points were gone.

**Comment by TeoTwawki** [comment]
This is intentional behavior - don't warp to otherwise inaccessible places and or that you haven't actually unlocked legit. The homepoint system in DSP is a buggy pos that we have no control over, we have no way to modify your stored homepoint data and the alternative is disabled the homepoint warping entirely.
