### ISSUE TITLE
Character Import: Storage, Locker, Satchel, Sack, Case, Wardrobe missing.

### ISSUE THREAD

**Issue by Baleoce** [LegionDark/Issues#830]
**Date & Time**: 16:32 BST - 01/04/2016

**FFXI Client Version (use `/ver`)**: version 30160203_0

**Character Name**: Bale

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 95RDM

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: X:0 Y:0 (88). (Windurst Waters Mog House)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: I recently requested a character import from retail (Cerberus). I didn't check at first (as my main inventory and my Mog Safe 1 were all intact), but eventually I looked and found that none of the following had been imported: Storage, Locker, Satchel, Sack, Case and Wardrobe.

**Comment by TeoTwawki** [comment]
Things I have to state to rule out a few things:

* Items over 75 and a few otherwise rare items are filtered out.

* items that were in storage will be non visible until furnishings bring the storage level back from zero to where it was

* some items may not actually exist on the server, and thus won't get imported (can check the item on the website tool)

* if using an outdated copy or the exporter or the library it depends on, there can be damaged/wrong data in import.

Items that definitely exist and should make the cut still missing after not being one of those 4 things?

**Comment by Baleoce** [comment]
Thanks for the reply Teo!

* Everything in all the above missing inventories were 75 or below (some rare/ex may not have been eligible, but there definitely would have been something in those inventories).
* I reseated all of the furniture from Mog Safe 1 in my mog house, logged out and back in, to make sure this wasn't the case. Nothing appeared in the inventories afterwards.
* Agreed, although again, at least 1 item would've been present in each inventory (presumably) as they were pretty much all 80/80 with potentially eligible items.
* Exporter was up to date.

Many thanks again :)

**Comment by TeoTwawki** [comment]
k, we'll try and see why this would happen on our end

**Comment by Baleoce** [comment]
Is it possible for the tool to miss things if you run it too quickly after logging into your character on retail?

**Comment by TeoTwawki** [comment]
maybe, retail does lag loading the inventory and equip quite a bit, and if its not in the client yet the tool can't read it

**Comment by TeoTwawki** [comment]
If you can re-attempt your export, lets try this again making sure all your data is fully loaded into your client before running the tool. 

Make sure to use the latest eliteapi http://ext.elitemmonetwork.com/downloads/eliteapi/  and client. There is an SE client update on the 5th so you'll want to hit it before that, since most servers will not have a matching version update right away.

**Comment by Baleoce** [comment]
Thanks Teo, I've now resubmitted the character xml data on the forums: http://legiondark.com/forums/viewtopic.php?f=37&t=1452

**Comment by TeoTwawki** [comment]
New xml file right?

**Comment by Baleoce** [comment]
That's right :)

**Comment by TeoTwawki** [comment]
Can you tell me one of the items that was missing before? checking something

**Comment by Baleoce** [comment]
One of the items in the Mog Wardrobe was a pair of Duelist's Boots.

**Comment by Baleoce** [comment]
ok the character has now been deleted and recreated.

**Comment by TeoTwawki** [comment]
Ok, check in game now - the import info shows the dualist boost (item ID 15136) got imported.

**Comment by Baleoce** [comment]
That all seems to be fixed now, many thanks Teo :)
