### ISSUE TITLE
PLD quest AF's story

### ISSUE THREAD

**Issue by Mojuroju** [LegionDark/Issues#86]
**Date & Time**: 12 - June- 2015
**Frequency**: Every time
**FFXI Client Version**: 30150508_8
**Character Name**: Radiantigress . But whichever i think
**Race**: Mithra . But wichever I think
**Main Job**: PLD at this moment.
**Sub Job**: WAR at this moment.
**Area & Coordinates**: X:-30 Y:4 :Z:-217 (137).
**Party or Solo**: I tried in party
**NPC Name**: Village Well
**Monster Name**: One-eyed_Gwajboj and  Three-eyed Prozpuz trading Well Weight (Item Id: 1095)
**Steps To Reproduce The Issue**:

I Know that i can find AFs with the guy at lower Jeuno (I already have the AF, it doesn't affect i think because i got the previous quest related with AF's feed), but i was doing the quest to see the story,and it was at the most excitment part, please don't spoiler me ;_;, the quest related is Under Oath you can find the steps here: http://ffxiclopedia.wikia.com/wiki/Under_Oath 
The issue is when you have to talk with the npc Village Well then its supposed the 2 NM cited before appear, and when you kill them ( in special One-eyed_Gwajboj i think) they drop Well Weight needed to continue the story trading the Well Weight to the Village Well in order to get a Key Item Knight's Confession, etc... etc...

Information added in a new comment down here

**Comment by TeoTwawki** [comment]
Sorry but the whole reason we started giving out free claim slips for the AF gear was because we can neither keep these quests working nor implement the missing ones (there is to much work to do for this server already), so even though you only want to do these for story purposes this is going to stay broken until its corrected in DarkStar itself. @Loki79 might be willing to get you past this broke spot but its not something we can keep doing for the next part(s) you run into that don't work or for everyone who decides to try them.

I suggest reporting AF quest issues you discover in the future directly to the DarkStar project, its your best shot for these eventually working like retail. Their tracker is here:  https://github.com/DarkstarProject/darkstar/issues/new

**Comment by Mojuroju** [comment]
Understood Boss ^.^

I was looking for info at DSP when i found that the problem it seem to be treaty. But it hasn't solved, beacuase i could pass trough. i will paste the links related

Link in where was asked : https://github.com/DarkstarProject/darkstar/pull/836

Link in where luas seem to be written: https://github.com/bobkornog/darkstar/commit/98032b06db2157d6b64f75d350874aff7974130d

Link in where specify lua part seem to be written: https://github.com/bobkornog/darkstar/blob/98032b06db2157d6b64f75d350874aff7974130d/scripts/zones/Davoi/npcs/Village_Well.lua

I hope this will be for help.

Sorry the troubles :S

**Comment by Loki79** [comment]
this may have been fixed many times and then broken by updates, after November things like should stay fixed since there will be no more updates but i doubt it will be addressed before then.
