### ISSUE TITLE
Upgrade White stratum abyssite from tier 4 to tier 5

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#912]
**Date & Time**: 4/28/16 2:43pm

**FFXI Client Version (use `/ver`)**:30160329_1 

**Character Name**: Baucant & Dapunted

**Nation**: Sandy

**Job(level)/Sub Job(level)**:BLU(99)/RDM(49) & WHM(99)/RDM(49) 

**NPC or Monster or item Name**: Key item White stratum abyssite V

**Zone name & Coordinates (use `@where`)**: Pashhow Marshlands [S] X:342 Y:25 Z:-159 (66)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: http://ffxiclopedia.wikia.com/wiki/A_New_Menace

After defeating all 3 NM Lancing Lamorak, Bhishani, & Rw Nw Prt M Hrw followed
http://legiondark.com/forums/viewtopic.php?f=40&t=1039&p=4309&hilit=voidwatch#p4309
when I went to Veridical Conflux i received a system message
Conditions not met.
Variable 'VW_3_Nations" value is:0
Quest "guardian_of_the_void" status is:2
Quest "a_cat_calls" status is:2

**Comment by TeoTwawki** [comment]
you missed a step and or multi-boxing ate one of your variable changes. which is why these prints are there (I got so sick of checking every individual)

**Comment by Baucant** [comment]
do we know which kill i need to do again or should i just assume i got none and re-kill all 3 again?

**Comment by TeoTwawki** [comment]
The variable is a binary bitmask, and I can't tell which one is which without looking up every NM (because nobody bloody commented in their scripts which VWNM is which chapter/tier they belong too let alone which bit in their mask they are) and then converting to decimal for which combination of NMs results in "2"..Its a huge pain in the rear.

Gimme which 3 and I will try and tell you, just this once. In the future I want some kind of system to straight up tell us whats missing but thats not easy to write.

**Comment by Baucant** [comment]
I don't mind killing them all again but the mobs are
Lancing Lamorak ID 17187289
Bhishani ID 17215956
Rw Nw Prt M Hrw 17252816

**Comment by TeoTwawki** [comment]
wait wait wait..wtf? Thats not the right thing you are even on. the conflux if for finishing off the 3 nation lines leading into Jeuno I go to check scripts and those are Jeuno line VW NMs. You have to have been previously pushed past some critical spot by a GM >.< and now everything is screwed up. GDI.

**Comment by TeoTwawki** [comment]
Talk on IRC.
