### ISSUE TITLE
The MOONLIT PATH

### ISSUE THREAD

**Issue by thicksz** [LegionDark/Issues#915]
**Date & Time**: 4/29/16 -12:06 est

**FFXI Client Version**: 30160329_1

**Character Name**: Hickss 

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: BLU99/RDM49 

**NPC or Monster or item Name**: Leepe-Hoppe 

**Zone name & Coordinates (use `@where`)**: windy water north X:13 Y:-9 Z:-197 (108) 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no 

**Steps To Reproduce / any other info**:I have lv 8 fame in al zone's needed. I have all 6 Whispers in temp KI. I did all SMN fights over to make sure but leepe-hoppe still will not give me KI to fight Fenrir...I had this done and all pet be4 update after that I was missing few pets on smn the rest are working 4 me but this one Moonlit path Leeepe-Hoppe will not give me KI moon light path why holding ALL 6 KI  whispers and the fame Needed. plz help with KI

**Comment by TeoTwawki** [comment]
@LegionDark/gm 2 possibilities here: **1** its broken in darkstar,  or **2** the fame change we don't have yet causes the game to state the player has much higher fame than they actually do (after the update I am pretty sure the fame level they are seeing now is what they will actually have, because the amount to reach that tier is what will be lowered).

**Comment by R3P0FFXI** [comment]
@thicksz Should now be resolved after maint
