### ISSUE TITLE
Resist Doom doesn't work the way Teo wants it to

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#926]
**Date & Time**: 5/2/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Pil

**Zone name & Coordinates (use `@where`)**: Any rift in Behemoth's Domain

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Pil's death move starts the countdown till death, half the time it works, half the time the count down counts down 2 or 3 numbers, after which the countdown just stops, and no one dies.  Happened during multiple pops, sometimes countdown worked, other times it would just stop.

**Comment by TeoTwawki** [comment]
"Pil's death move" got a name spectre? coz I don't like having to look up every move a mob has to find what ppl are talking about.

**Comment by Genesis-Legion** [comment]
The move seemed to be Royal Decree

**Comment by spectre99** [comment]
Yeah I believe that is the move.  Sorry we actually did the fight a few days ago and I don't have a t3 pop anymore so couldn't pop to see.

**Comment by TeoTwawki** [comment]
ok got it figured out. in  #929 I mentioend DSP is handling status resistance incorrectly. Also, DSp does not _have_ a resist doom. But we do. You got a partial resist on doom which cut the duration. What should have happened was a message saying doom didn't hit you at all, but instead you got a doom that simply wore off before it could kill you. Thank your ring.

Expected behavior: resist check rolled AFTER macc vs meva check, resisted effect doesn't land at all.
Actual Darkstar behavior: effect duration altered based on the macc vs meva check with resist stat being added into meva.

**Comment by TeoTwawki** [comment]
Fix will be in next maintenance :) got all resisty things working properly, even made the message slightly special for a certain augment ring's resist doom proc.

**Comment by TeoTwawki** [comment]
Fixed with today's update.
