### ISSUE TITLE
Rail Cannon learnable from different mob than listed in BLU tool

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#934]
**Date & Time**: 
05/07/2016 - 10:29

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Buttons

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU(99)/RDM(49)

**NPC or Monster or item Name**: 
Sub-Zero Gear

**Zone name & Coordinates (use `@where`)**: 
Abyssea-Uleguearand

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
I learned Rail Cannon from a Sub-Zero Gear in Abby-Uleguearand. I've never even seen a Chariot, and don't know what they are. According to the BLU tool on the website, they're the only way to get Rail Cannon. Per FFXI Wikia, Chariots don't even have that TP move.

**Comment by Genesis-Legion** [comment]
Someone else can correct me if I'm wrong, but I recall that learning Rail Cannon from Sub-Zero Gears a "Loki fix" for people to be able to learn the spell at all. (just have to kill the gear, not learn it normally"

**Comment by atom0s** [comment]
Mid also made a ticket on the website tracker here:
https://github.com/LegionDark/Website/issues/33

As I stated there, this issue on the site is due to the learning stuff being in the monsters script and not in the database like the others. I'm sure there are others out there that are implemented in the same fashion as a workaround that will sooner or later need to be put into the database once the monsters are properly implemented.

**Comment by atom0s** [comment]
Marking this closed as the report is not actually a bug but how things are implemented.
