### ISSUE TITLE
Mog Safe 2 and no LS after transfer

### ISSUE THREAD

**Issue by Falendria** [LegionDark/Issues#938]
**Date & Time**: May 5th

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Falendria

**Nation**: Windurst

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: Mog House

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: N/A, I had items my my Mog Safe 2 before my transfer from BNET.cc FFXI server, and when my transfer was finished i also have no LS. I was just hoping to see if we could remedy either or both of these if possible. Thank You.

**Comment by R3P0FFXI** [comment]
@Falendria If Bnet.CC had Mogsafe 2 running that's news to me as DSP doe snot have that coded yet. Also your LS would need to be recreated that would never transfer from server to server even on SE transfer service.

**Comment by Falendria** [comment]
I didn't have a LS on BNET, i was saying i need the LS for DSP so i can talk to everyone. on BNET /say chat was server wide so we didn't need a LS. Also here's a picture of me in my mog safe 2. The contents have changed since in a recent update something got messed up and they had to revert to an old backup.
![img_20160510_090650](https://cloud.githubusercontent.com/assets/19287687/15149366/cc41ecbe-168e-11e6-81f5-9bdafe7a3e45.png)

**Comment by R3P0FFXI** [comment]
@Falendria Mog Safe 2 is not open on Legion, there is nothing we can do to fix this if Bnet.CC changed something.

http://legiondark.com/forums/viewtopic.php?f=37&t=1163

It is possible DSP fixed Mogsafe 2 on the current version they are running I dont know I just know Mogsafe 2 is NOT open on legion at this time. We had a notice posted on the forums advising everyone of this Since Dec 10 as you can see above.

**Comment by TeoTwawki** [comment]
dsp only just added mogsafe2, its super recent on the master branch. legions won't have that for several weeks at the earliest, those items may possibly be present but invisible because of the invalid container, or they might be lost. either way nothing we can do about them for you.

The linkshell, any GM can pearl you via a command I wrote so I'm passing assignee to Gene

**Comment by Falendria** [comment]
Thank you both =3 It's okay about the items, i simply misread the post and thought they might be movable. But even if they are gone it's okay, thank you for the quick responses^^

**Comment by Genesis-Legion** [comment]
Hooked Falendria up with the server LS, should be sorted out now.
