### ISSUE TITLE
Tp regain items

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#947]
**Date & Time**: 23.04

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Clay

**Nation**: SAndoria

**Job(level)/Sub Job(level)**: 99war/49dnc

**NPC or Monster or item Name**: Karieyh ring

**Zone name & Coordinates (use `@where`)**:  

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27587/karieyh-ring

**Multi-boxing? (multiple clients on same connection)**:yes

**Steps To Reproduce / any other info**:  first of all i know it is a dsp bug they seem to not fix it like forever. Are there any plans of fixing tp regain items ? right now you gain 1/10th of retail.

**Comment by R3P0FFXI** [comment]
@benfolka This has been working with the same stats as Retail since the day it was introduced so not sure what your talking about

**Comment by benfolka** [comment]
at 100 tp you ws on retail is that correct ?
we ws at tp 1000 
so karieyh ring shall give 50 tp instead of 5
i might be wrong, i may be misinformed about it.

**Comment by TeoTwawki** [comment]
Retail and dsp used to use scale of 0~300 and now both use 0~3000 (in actuality, its just we could not see the next digit over, was only a display change).

If the item exists on [unmodified DSP](https://github.com/DarkstarProject/darkstar) and gives the wrong amount, it needs reported to [their tracker](https://github.com/DarkstarProject/darkstar/issues/new) instead of Legions. If the item only exists on Legion, somebody here derped/missed the memo on tp stuffs. Betting on the latter, I don't think that item works in stock DSP yet.

**Comment by benfolka** [comment]
if ticket needs to be closed, you can close it.
thank you.
